### ISSUE TITLE
Migration scripts for v12

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/OpenUpgrade#1448]
`(del)` means that the module has been removed in this version
`(add)` means that the module has been added in this version
`>` means that it has been identified that the module has been renamed to the name below
`->` means that the module has been merged in another existing module.

- models:
  - [x] `account.payment.term` model has now multi-company security rule (odoo/odoo@4868ba78ff5caa4cfa724ada5f3834f1512e44cd). The safest option is to deactivate the rule on post migration. - By @mreficent / @pedrobaeza - #1677 
  - [x] Several groups moved from `sale` to `account`: odoo/odoo@3ec6294739d19e2c263c270b49483199121a02c0 - By @mreficent - #1677
  - [x] Merged push and pull rules in odoo/odoo@a35df8d37170790257876a54aa54f2c3ab596c44 - By @mreficent - #1681
  - [x] `procurement.rule` renamed to `stock.rule` in odoo/odoo@827958a8902589246dd741341ce1bc5465059909 - By @mreficent - #1681
  - [x] sections are moved from `sale` to `account`: odoo/odoo@762adedece1c6c2b97b282348659c1b39b988d24 - By @mreficent - #1677
  - [x] Translations comments are changed in https://github.com/odoo/odoo/pull/26925/files#diff-a41938cd3ff4c7e353103fcd581f839a (to be handled on `base`). Important comment about this on https://github.com/odoo/odoo/pull/26925#issuecomment-422445897
  - [x] account reports moved to enterprise (https://github.com/odoo/odoo/commit/e51b4f659fc5e4253d3156754ada21166c8d1bf8) - Replaced by `account_financial_report` OCA module.

OCA has funded the development of the migration scripts that are installed in their Odoo instance. They are marked as `(OCA project)` for being recognized and expect them to be done in the near future if not yet done.

- [x] account (OCA project) - By @mreficent / @pedrobaeza - #1677
- [x] account_analytic_default - By @pedrobaeza - #1996 
- [x] (del) account_asset (https://github.com/odoo/odoo/commit/2e63ead842a0d2ccd3a78e9453e6d224650b8790) [moved to enterprise] - Replaced by https://github.com/OCA/account-financial-tools/tree/12.0/account_asset_management
- [x] account_bank_statement_import (OCA project) - By @mreficent - #1804
- [x] (del) account_budget (https://github.com/odoo/odoo/commit/2870af948e237e557f39287929e1a30de2c25730) [moved to enterprise] - Replaced by https://github.com/OCA/account-budgeting/tree/12.0/account_budget_oca
- [x] account_cancel (OCA project) - By @mreficent - #1806
- [x] (del) account_cash_basis_base_account (OCA project) `->` account (https://github.com/odoo/odoo/commit/bfe362c87a2c058c9257166dca096d80c79d3dc3 ) [technically the module was a backport of this commit] - By @mreficent - #1677
- [x] account_check_printing - By @mreficent - #1805
- [ ] (new) account_facturx (https://github.com/odoo/odoo/commit/380f1c09ce2399761f4cf8ae74dafcfb05aa3deb)
- [x] (del) account_invoicing (OCA project) `->` account (https://github.com/odoo/odoo/commit/a701031c929f22095e062fe1da238d8cffacd73e) - By @mreficent - #1677
- [ ] account_lock
- [x] account_payment - By @mreficent - #1680
- [x] account_tax_python - By @KareemAbuzaid - #2225 
- [x] account_test - By @KareemAbuzaid - #2227 
- [x] account_voucher (OCA project) - By @mreficent - #1727
- [x] analytic (OCA project) - By @mreficent / @pedrobaeza - #1662
- [ ] (del) anonymization (https://github.com/odoo/odoo/commit/c8a4f42ef8d2d03083471370244a8bf3855d9d76)
- [x] association (OCA project) - By @mreficent - #1807
- [x] (del) auth_crypt (OCA project) `->` base (https://github.com/odoo/odoo/commit/a06066b920f5d59105dc285cf3f0f0f77da8cd80) - By @StefanRijnhart - #1531
- [x] auth_ldap - By @mreficent - #1562
- [x] auth_oauth (OCA project) - By @mreficent - #1689
- [ ] (new) auth_password_policy (https://github.com/odoo/odoo/commit/efb516e045031ccc576fa5c0e4f03d6967538a9d)
- [ ] (new) auth_password_policy_signup (https://github.com/odoo/odoo/commit/a47f6093f80cefa51c5a1bc1301db01007f97761)
- [x] auth_signup (OCA project) - By @mreficent / @pedrobaeza - #1552
- [x] barcodes (OCA project) - By @mreficent - #1543
- [x] base (OCA project) - By @StefanRijnhart - #1531 
- [x] base_address_city - By @mreficent - #1844
- [x] base_address_extended - By @mreficent - #1844
- [x] base_automation (OCA project) - By @mreficent - #1728
- [x] base_gengo - By @mreficent - #1553
- [x] base_geolocalize (OCA project) - By @mreficent - #1729
- [x] base_iban (OCA project) - By @mreficent - #1803
- [x] base_import (OCA project) - By @mreficent - #1566
- [ ] base_import_module
- [x] base_setup (OCA project) - By @mreficent - #1564
- [x] base_sparse_field - By @mreficent - #1563
- [x] base_vat (OCA project) - By @mreficent - #1730
- [x] base_vat_autocomplete (OCA project) `>` partner_autocomplete (https://github.com/odoo/odoo/commit/8a1815b31eacc148d6e98795899ee24a9ca8cab1) [extension]  - By @mreficent - #1731 
- [x] board (OCA project) - By @mreficent - #1541
- [x] bus (OCA project) - By @mreficent - #1551
- [x] calendar (OCA project) - By @mreficent / @pedrobaeza - #1547
- [x] calendar_sms (OCA project) - By @mreficent - #1691
- [x] contacts (OCA project) - By @mreficent - #1550
- [x] crm (OCA project) - By @mreficent / @pedrobaeza - #1579
- [x] crm_livechat - By @mreficent - #1690
- [x] crm_phone_validation  - By @mreficent - #1555
- [x] crm_project - By @mreficent - #1674 
- [ ] (new) crm_reveal (https://github.com/odoo/odoo/commit/eebaf55fde2fea1a4d4fefedc5183fe959fb2660)
- [x] decimal_precision (OCA project) - By @mreficent - #1560
- [x] delivery - By @pedrobaeza - #1926 
- [x] (new) digest (https://github.com/odoo/odoo/commit/2d1abe64e433acdf95d58fedc736247829dc748c) - By @mreficent - #1576
- [x] document (OCA project) - By @mreficent - #1549
- [x] event (OCA project) - By @mreficent - #1663
- [x] event_sale (OCA project) - By @mreficent - #1808
- [x] fetchmail (OCA project) - By @mreficent - #1573
- [x] fleet - By @astirpe - #1913
- [x] gamification - By @pedrobaeza - #3016 
- [ ] gamification_sale_crm
- [x] google_account - By @mreficent - #1845
- [x] google_calendar - By @mreficent - #1845
- [x] google_drive - By @mreficent - #1845
- [x] google_spreadsheet - By @mreficent - #1845
- [x] hr (OCA project) - By @mreficent - #1675
- [x] hr_attendance - By @mreficent - #1688
- [x] hr_contract - By @mreficent / @pedrobaeza  - #1738
- [x] hr_expense - By @mreficent - #1740
- [x] hr_expense_check - By @mreficent - #1740
- [ ] hr_gamification
- [x] hr_holidays - By @mreficent / @pedrobaeza - #1722
- [x] hr_maintenance - By @mreficent - #1692
- [x] hr_org_chart - By @mreficent - #1726
- [x] hr_payroll - By @mreficent - #1940
- [x] hr_payroll_account - By @mreficent - #1940
- [x] hr_recruitment - By @mreficent / @pedrobaeza  - #1725
- [x] hr_recruitment_survey - By @mreficent - #1725
- [x] hr_timesheet (OCA project) - By @mreficent - #1723
- [x] hr_timesheet_attendance - By @mreficent - #1723
- [x] http_routing (OCA project) - By @mreficent - #1558
- [x] iap (OCA project) - By @mreficent - #1566
- [x] im_livechat - By @mreficent - #1690
- [x] (new) im_livechat_mail_bot (https://github.com/odoo/odoo/commit/cf505c36985221819139ce30d7f03e6e51ec0298) - By @mreficent - #1692 
- [ ] (new) im_support (https://github.com/odoo/odoo/commit/2aeb7637689e3bd0e124b8effeb3f294e80eaad1)
- [x] l10n_be - By @mreficent - #1939
- [x] l10n_be_invoice_bba - By @mreficent - #1939
- [x] l10n_ch (OCA project) - By @mreficent - #1743
- [x] l10n_es - By @pedrobaeza - #1872
- [x] l10n_fr - By @pedrobaeza - #2515 
- [x] l10n_generic_coa - By @mreficent - #1742
- [x] l10n_ma - Nothing to do - 1e15f921800e9ea998d8de884e55a4dd087e55cc
- [x] l10n_multilang (OCA project) - By @mreficent - #1743
- [x] l10n_nl - By @astirpe - #1802
- [x] l10n_pt - By @pedrobaeza - #3197 
- [x] link_tracker (OCA project) - By @mreficent - #1561
- [x] lunch - By @mreficent - #1574
- [x] mail (OCA project) - By @mreficent / @pedrobaeza - #1569
- [x] (new) mail_bot (https://github.com/odoo/odoo/commit/cf505c36985221819139ce30d7f03e6e51ec0298) - By @mreficent - #1692 
- [x] maintenance - By @mreficent - #1676
- [x] mass_mailing - By @mreficent / @pedrobaeza - #1664
- [x] (new) mass_mailing_crm (https://github.com/odoo/odoo/commit/f028ba56d1de84739ca7eb70eae3687b94957895) - By @mreficent - #1692 
- [x] mass_mailing_event - By @OthmaneGhandi - #1990
- [ ] mass_mailing_event_track
- [ ] (new) mass_mailing_sale (https://github.com/odoo/odoo/commit/a18ff88b4239c3c46c18616bf44e175dca453f2a)
- [x] membership (OCA project) - By @mreficent - #1807
- [x] mrp - By @mreficent - #1683 
- [x] mrp_byproduct - By @mreficent - #1936
- [x] mrp_repair `>` repair (https://github.com/odoo/odoo/commit/c16c46a00d6bb2755159531a393e2321b486966c) - By @mreficent - #1734 
- [x] note - By @mreficent - #1732
- [x] note_pad - By @mreficent - #1732
- [x] pad (OCA project) - By @mreficent - #1556
- [x] pad_project (OCA project) - By @mreficent - #1674
- [x] payment (OCA project) - By @mreficent - #1679
- [x] payment_adyen - By @mreficent - #1835
- [x] payment_authorize - By @mreficent - #1835
- [x] payment_buckaroo - By @mreficent - #1835
- [x] payment_ogone - By @mreficent - #1835
- [x] payment_paypal (OCA project) - By @mreficent - #1835
- [x] payment_payumoney - By @mreficent - #1835
- [x] payment_sips - By @mreficent - #1835
- [x] payment_stripe - By @mreficent - #1835
- [x] payment_transfer (OCA project) - By @mreficent - #1835
- [x] phone_validation - By @mreficent - #1555
- [x] point_of_sale (OCA project) - By @mreficent / @pedrobaeza - #1717
- [x] portal (OCA project) - By @mreficent / @pedrobaeza - #1546
- [ ] pos_cache
- [ ] (del) pos_data_drinks (https://github.com/odoo/odoo/commit/bed29a4aeab0ec6ef0c02975ee86655d6a030299)
- [x] pos_discount - By @chienandalu - #2410 
- [ ] pos_mercury
- [x] pos_reprint - By @chienandalu - #2410 
- [x] pos_restaurant - By @mreficent - #1717
- [x] pos_sale (OCA project) - By @mreficent - #1855
- [x] procurement_jit (OCA project) - By @mreficent - #1857
- [x] product  (OCA project) - By @PCatinean / @pedrobaeza - #1533 
- [ ] product_email_template
- [x] product_expiry - By @sergio-teruel - #2097 
- [x] product_extended `>` mrp_bom_cost (https://github.com/odoo/odoo/commit/8f268469d52b34e4d09333eec56f2afbfd7f7ec6)
- [x] product_margin - By @pedrobaeza - #2084
- [x] project (OCA project) - By @mreficent / @pedrobaeza - #1674
- [x] project_timesheet_holidays - By @mreficent - #1723
- [x] purchase (OCA project) - By @mreficent / @pedrobaeza - #1712
- [x] purchase_mrp - By @mreficent - #1936
- [x] purchase_requisition - By @mreficent - #1938
- [x] (new) purchase_stock (https://github.com/odoo/odoo/commit/4232eb7bcd4dd895b86db728a2b689ae9568f951) - By @mreficent / @pedrobaeza - #1712
- [x] rating (OCA project) - By @mreficent - #1554
- [x] (del) rating_project `->` project (https://github.com/odoo/odoo/commit/95698bd408a29cb2ebc4abe0445a4739eceba082) - By @mreficent - #1674
- [ ] (del) report_intrastat (https://github.com/odoo/odoo/commit/c75f3a007c89ec16d7cca4d9f80659eec9e4e772) [moved to enterprise]
- [x] resource (OCA project) - By @mreficent / @pedrobaeza - #1578
- [x] sale (OCA project) - By @mreficent / @pedrobaeza - #1711
- [x] sale_crm (OCA project) - By @mreficent - #1716
- [x] sale_expense - By @OthmaneGhandi - #1887 
- [x] sale_management (OCA project) - By @mreficent - #1716
- [x] sale_margin - By @mreficent - #1937
- [x] sale_mrp - By @mreficent - #1936
- [x] (del) sale_order_dates `->` sale & sale_stock (https://github.com/odoo/odoo/commit/867e47927dc9e38f397f8abc4dc5e295784331b4) - By @mreficent - #1711
- [x] (del) sale_payment (OCA project) `->` sale (https://github.com/odoo/odoo/commit/4c31a758cf0715b1c1ff2f5b3cef18fec92c2d84) - By @mreficent - #1711
- [x] (new) sale_purchase (https://github.com/odoo/odoo/commit/6ea10114160c9f2f61347f3a54e3ff07a6d79b40) - By @pedrobaeza - #2003 
- [x] (del) sale_service_rating `->` sale_timesheet (https://github.com/odoo/odoo/commit/95698bd408a29cb2ebc4abe0445a4739eceba082) - By @mreficent - #1739
- [x] sale_stock (OCA project) - By @mreficent - #1857 - By @pedrobaeza - #2544 
- [x] sale_timesheet (OCA project) - By @mreficent - #1739
- [x] sales_team (OCA project) - By @mreficent - #1577
- [x] sms (OCA project) - By @mreficent - #1684
- [x] (new) snailmail (https://github.com/odoo/odoo/commit/4cb91942751130f003a5c2a8dce545a7cd877bee) - By @mreficent - #1692 
- [ ] (new) snailmail_account (https://github.com/odoo/odoo/commit/53cdd68e7cc9e1494a9a99dcd2fff0cc835eab50)
- [x] (new) social_media (https://github.com/odoo/odoo/commit/9a7fd72197799c0815f0d2e0ed4f895f674a053d) - By @mreficent - #1673
- [x] stock (OCA project) - By @mreficent / @pedrobaeza - #1681
- [x] stock_account (OCA project) - By @mreficent - #1681
- [x] stock_dropshipping - By @pedrobaeza - #2003 
- [x] stock_landed_costs - By @pedrobaeza - #2968 
- [x] stock_picking_batch - By @pedrobaeza - #2282 
- [ ] (new) stock_zebra (https://github.com/odoo/odoo/commit/77d8d45d7fe90f3488e78775bdf480e4a51daf31)
- [x] survey (OCA project) - By @mreficent - #1575
- [x] survey_crm (OCA project) - By @mreficent - #1575
- [x] theme_bootswatch - By @mreficent - #1842
- [x] theme_default - By @mreficent - #1842
- [x] transifex - By @mreficent - #1557
- [x] (new) uom (https://github.com/odoo/odoo/commit/6a378e383910ab597359f95c38028b229fc82cc7) - By @PCatinean - #1533 
- [x] utm (OCA project) - By @mreficent - #1548
- [x] web (OCA project) - By @mreficent - #1531
- [x] web_diagram (OCA project) - By @mreficent - #1566
- [x] web_editor (OCA project) - By @mreficent - #1566
- [x] web_kanban_gauge (OCA project) - By @mreficent - #1566
- [x] (del) web_planner (OCA project) (https://github.com/odoo/odoo/commit/7ed9a7fabeb613bf8b2c2980190399e8f9bbaa2b) - By @mreficent - #1566
- [x] web_settings_dashboard (OCA project) - By @mreficent - #1566
- [x] web_tour (OCA project) - By @mreficent - #1566
- [x] (new) web_unsplash (https://github.com/odoo/odoo/commit/732702d5e2a007797e589dc42b29f31a9e27c54f) - By @mreficent - #1566
- [x] website (OCA project) - By @mreficent / @pedrobaeza - #1685 - BS4 conversion pending
- [x] website_blog (OCA project) - By @mreficent - #1837
- [x] website_crm (OCA project) - By @mreficent - #1836
- [x] website_crm_partner_assign (OCA project) - By @mreficent - #1841
- [x] website_crm_phone_validation - By @pedrobaeza - #2007 
- [x] website_customer (OCA project) - By @mreficent - #1841
- [x] website_event (OCA project) - By @mreficent - #1828
- [x] website_event_questions - By @pedrobaeza - #2008
- [x] website_event_sale (OCA project)  - By @mreficent - #1858
- [x] website_event_track - By @Yajo - #1921 
- [x] website_form (OCA project) - By @mreficent - #1823
- [x] website_form_project (OCA project) - By @mreficent - #1823
- [ ] website_forum
- [x] website_gengo - By @mreficent - #1831
- [x] website_google_map (OCA project) - By @mreficent - #1830
- [x] website_hr (OCA project) - By @mreficent - #1824
- [x] website_hr_recruitment - By @mreficent - #1833
- [x] website_links (OCA project) - By @mreficent - #1827
- [x] website_livechat - By @mreficent - #1834
- [x] website_mail (OCA project) - By @mreficent - #1825
- [x] website_mail_channel (OCA project) - By @mreficent - #1825
- [x] website_mass_mailing - By @Yajo - #1922 
- [x] website_membership (OCA project)  - By @mreficent - #1858
- [x] website_partner (OCA project) - By @mreficent - #1822 - By @pedrobaeza - #1839 
- [x] website_payment (OCA project) - By @mreficent - #1826
- [x] website_quote  `>` sale_quotation_builder (https://github.com/odoo/odoo/commit/4c31a758cf0715b1c1ff2f5b3cef18fec92c2d84) [some things went to sale/sale_management]  - By @mreficent - #1951
- [x] website_rating (OCA project) - By @mreficent - #1832
- [x] (del) website_rating_project `->` project (https://github.com/odoo/odoo/commit/d7d30f69d78e75cb859ec6b5e70b91d78c6e4eaf) - By @mreficent - #1674
- [x] website_sale (OCA project) - By @mreficent / @pedrobaeza - #1843
- [x] website_sale_comparison - By @sergio-teruel - #2098 
- [x] website_sale_delivery - By @sergio-teruel - #2096 
- [x] website_sale_digital (OCA project)  - By @mreficent - #1858
- [ ] (new) website_sale_link_tracker (https://github.com/odoo/odoo/commit/a924cbf98333fdd3d63d96254d189cb25cf2246a)
- [x] website_sale_management (OCA project)  - By @mreficent - #1858
- [x] (del) website_sale_options `->` website_sale & sale (https://github.com/odoo/odoo/commit/856c2e9008f1af7bc1327d9c2900db1e109ab0fa) - By @mreficent - #1608
- [x] website_sale_stock (OCA project)  - By @mreficent - #1858
- [x] (del) website_sale_stock_options `->` website_sale_stock (https://github.com/odoo/odoo/commit/856c2e9008f1af7bc1327d9c2900db1e109ab0fa)
- [x] website_sale_wishlist - By @sergio-teruel - #2102 
- [x] website_slides - By @pedrobaeza - #1917 
- [ ] (new) website_survey (https://github.com/odoo/odoo/commit/3c0daf39e96461a358b0e73811bb2d5ed496d916)
- [x] website_theme_install (OCA project) - By @mreficent - #1842
- [x] website_twitter - By @pedrobaeza - #2129

**Comment by pedrobaeza** [comment]
As other times, I open this issue early for taking notes of the things we discover in master branch that will affect migration scripts.

**Comment by sbidoul** [comment]
> The safest option is to erase field company_id in all existing records for not altering the behavior.

Or deactivating the record rule? Erasing the field sounds dangerous, as people may have added the record rule themselves.

**Comment by pedrobaeza** [comment]
You are right, changed.

**Comment by MiquelRForgeFlow** [comment]
For modules, the changes has been:

- additions:
(add) account_facturx (https://github.com/odoo/odoo/commit/380f1c09ce2399761f4cf8ae74dafcfb05aa3deb)
(add) digest (https://github.com/odoo/odoo/commit/2d1abe64e433acdf95d58fedc736247829dc748c)
(add) im_support (https://github.com/odoo/odoo/commit/2aeb7637689e3bd0e124b8effeb3f294e80eaad1)
(add) iot (https://github.com/odoo/odoo/commit/92172d02292a3d18a0d928cf9e5444a90ac4ac5a)
(add) l10n_hk (https://github.com/odoo/odoo/commit/c6bba1a6cd3ad434c41bbf7f14c4c0051f0b1399)
(add) mail_bot (https://github.com/odoo/odoo/commit/cf505c36985221819139ce30d7f03e6e51ec0298)
(add) snailmail (https://github.com/odoo/odoo/commit/4cb91942751130f003a5c2a8dce545a7cd877bee)
(add) social_media (https://github.com/odoo/odoo/commit/9a7fd72197799c0815f0d2e0ed4f895f674a053d)
(add) stock_zebra (https://github.com/odoo/odoo/commit/77d8d45d7fe90f3488e78775bdf480e4a51daf31)
(add) web_unsplash (https://github.com/odoo/odoo/commit/732702d5e2a007797e589dc42b29f31a9e27c54f)

- additions (bridges):
(add bridge) im_livechat_mail_bot (https://github.com/odoo/odoo/commit/cf505c36985221819139ce30d7f03e6e51ec0298)
(add bridge) mass_mailing_crm (https://github.com/odoo/odoo/commit/f028ba56d1de84739ca7eb70eae3687b94957895)
(add bridge) mass_mailing_sale (https://github.com/odoo/odoo/commit/a18ff88b4239c3c46c18616bf44e175dca453f2a)
(add bridge) sale_purchase (https://github.com/odoo/odoo/commit/6ea10114160c9f2f61347f3a54e3ff07a6d79b40)
(add bridge) website_sale_link_tracker (https://github.com/odoo/odoo/commit/a924cbf98333fdd3d63d96254d189cb25cf2246a)

- additions (splits):
(add bridge - split from account/snailmail) snailmail_account (https://github.com/odoo/odoo/commit/53cdd68e7cc9e1494a9a99dcd2fff0cc835eab50)
(add bridge - split from purchase) purchase_stock (https://github.com/odoo/odoo/commit/4232eb7bcd4dd895b86db728a2b689ae9568f951)
(add - split from test_performance and mail) test_mail (https://github.com/odoo/odoo/commit/21ad8d25886b8e7ca8bfe5492c3e76fe001f9a51)
(add - split from product) uom (https://github.com/odoo/odoo/commit/6a378e383910ab597359f95c38028b229fc82cc7)
(add bridge - split from survey) website_survey (https://github.com/odoo/odoo/commit/3c0daf39e96461a358b0e73811bb2d5ed496d916)

- renames:
mrp_repair > repair (https://github.com/odoo/odoo/commit/c16c46a00d6bb2755159531a393e2321b486966c)
product_extended > mrp_bom_cost (https://github.com/odoo/odoo/commit/8f268469d52b34e4d09333eec56f2afbfd7f7ec6)
website_quote  > sale_quotation_builder (https://github.com/odoo/odoo/commit/4c31a758cf0715b1c1ff2f5b3cef18fec92c2d84) [some things went to sale/sale_management]

- merges:
(del) account_cash_basis_base_account -> account (https://github.com/odoo/odoo/commit/bfe362c87a2c058c9257166dca096d80c79d3dc3)[technically the module was a backport of this commit]
(del) account_invoicing -> account (https://github.com/odoo/odoo/commit/a701031c929f22095e062fe1da238d8cffacd73e)
(del) auth_crypt -> base (https://github.com/odoo/odoo/commit/a06066b920f5d59105dc285cf3f0f0f77da8cd80)
(del) rating_project -> project (https://github.com/odoo/odoo/commit/95698bd408a29cb2ebc4abe0445a4739eceba082)
(del) sale_order_dates -> sale/sale_stock (https://github.com/odoo/odoo/commit/867e47927dc9e38f397f8abc4dc5e295784331b4)
(del) sale_payment -> sale (https://github.com/odoo/odoo/commit/4c31a758cf0715b1c1ff2f5b3cef18fec92c2d84)
(del) sale_service_rating -> sale_timesheet (https://github.com/odoo/odoo/commit/95698bd408a29cb2ebc4abe0445a4739eceba082)
(del) website_rating_project -> project (https://github.com/odoo/odoo/commit/d7d30f69d78e75cb859ec6b5e70b91d78c6e4eaf)

- removes:
(del) anonymization (https://github.com/odoo/odoo/commit/c8a4f42ef8d2d03083471370244a8bf3855d9d76)
(del - moved to enterprise) l10n_be_intrastat (https://github.com/odoo/odoo/commit/c75f3a007c89ec16d7cca4d9f80659eec9e4e772)
(del) pos_data_drinks (https://github.com/odoo/odoo/commit/bed29a4aeab0ec6ef0c02975ee86655d6a030299)
(del - moved to enterprise) report_intrastat (https://github.com/odoo/odoo/commit/c75f3a007c89ec16d7cca4d9f80659eec9e4e772)
(del) web_planner (https://github.com/odoo/odoo/commit/7ed9a7fabeb613bf8b2c2980190399e8f9bbaa2b)

@pedrobaeza when your first post gets updated with this post, I will delete it.

**Comment by pedrobaeza** [comment]
Included, and I have already hidden the comment.

**Comment by Rathnakreeswaran** [comment]
how you guys are dealing the migration script without odoo 12 addons ?

**Comment by pedrobaeza** [comment]
See https://github.com/OCA/OpenUpgrade/issues/1448#issuecomment-404676317

**Comment by MiquelRForgeFlow** [comment]
Updated issue putting full working list.

**Comment by pedrobaeza** [comment]
OK

**Comment by pedrobaeza** [comment]
@mreficent you should add ` (OCA project)` to the modules that are covered by the OCA RfQ in the list.

**Comment by MiquelRForgeFlow** [comment]
done

**Comment by pedrobaeza** [comment]
Great, thanks!

**Comment by erobotics** [comment]
Is it ready to use yet? when I run the script it seems can only upgrade to v11, thanks

**Comment by pedrobaeza** [comment]
See the coverage above. Any way, the migrate.py script is not suitable for migrating to latest versions.

**Comment by erobotics** [comment]
> See the coverage above. Any way, the migrate.py script is not suitable for migrating to latest versions.

Thank you for replying to me. I will try to manually migrate it over. It is a pain to migrate each time.

**Comment by crbll0** [comment]
**Greetings to all**
Could you tell me how I can use openupgrade (what are the steps) to migrate from v11 to v12, because it is not clear to me how I should use it.

_Sorry for the inconvenience, but on the internet I can't find clear information on how it is used._

**Comment by dupski** [comment]
@crbll0 https://doc.therp.nl/openupgrade/

**Comment by pedrobaeza** [comment]
It can be considered finished.
