### ISSUE TITLE
Migration to version 15.0

### ISSUE THREAD

**Issue by legalsylvain** [OCA/OpenUpgrade#3287]
- Full list of modules available here : https://github.com/OCA/OpenUpgrade/blob/15.0/docsource/modules140-150.rst 

# Pending / done work

- [x] account - By @MiquelRForgeFlow - #3505
- [x] account_check_printing - By @MiquelRForgeFlow - #3515
- [x] account_debit_note - By @pedrobaeza - #4202
- [x] account_edi - By @duong77476 - #3314
- [x] account_edi_facturx - By @duong77476 - #3373
- [x] account_edi_ubl - By @duong77476 - #3374
- [x] account_fleet - By @pedrobaeza - #4505
- [x] account_invoice_report_utm_campaign - By @nayatec - #4599
- [x] account_payment - By @duong77476 - #3375
- [x] account_qr_code_sepa - By @pedrobaeza - #4209
- [x] analytic - By @sang250399 - #3271 
- [x] association - By @pedrobaeza - #4043
- [x] attachment_indexation - By @legalsylvain - #3366
- [x] auth_ldap - By @pedrobaeza - #4399
- [x] auth_oauth - By @MiquelRForgeFlow - #3467
- [x] auth_password_policy - By @sergio-teruel - #3638
- [x] auth_password_policy_signup - By @sergio-teruel - #3637
- [x] auth_signup - By @MiquelRForgeFlow - #3463
- [x] auth_totp - By @MiquelRForgeFlow - #3480
- [x] auth_totp_portal - By @MiquelRForgeFlow - #3484
- [x] barcodes - By @sang250399 - #3301
- [x] base - By @MiquelRForgeFlow - #2967
- [x] base_address_city - By @pedrobaeza - #3635
- [x] base_address_extended - By @pedrobaeza - #4403
- [x] base_automation - By @legalsylvain - #3367
- [x] base_geolocalize - By @duong77476 - #3377
- [x] base_iban - By @legalsylvain - #3368
- [x] base_import - By @legalsylvain - #3369
- [x] base_setup - By @sang250399 - #3268
- [x] base_sparse_field - By @hhgabelgaard - #3601
- [x] base_vat - By @duong77476 - #3378
- [x] board - By @legalsylvain - #3370
- [x] bus - By @sang250399 - #3270
- [x] calendar - By @MiquelRForgeFlow - #3466
- [x] calendar_sms - By @legalsylvain - #3371
- [x] contacts - By @legalsylvain - #3372
- [x] coupon - By @pedrobaeza - #3754
- [x] crm - By @MiquelRForgeFlow - #3502
- [x] crm_iap_lead - By @MiquelRForgeFlow - #3565
- [x] crm_iap_lead_enrich - By @duong77476 - #3380
- [x] crm_iap_lead_website - By @duong77476 - #3382
- [x] crm_livechat - By @MiquelRForgeFlow - #3736
- [x] crm_sms - By @MiquelRForgeFlow - #3522
- [x] delivery - By @hieu1211 / @pedrobaeza - #3752
- [x] digest - By @cuongnmtm - #4167
- [x] event - By @MiquelRForgeFlow - #3500
- [x] event_crm - By @MiquelRForgeFlow - #3521
- [x] event_sale - By @MiquelRForgeFlow - #3520
- [x] event_sms - By @MiquelRForgeFlow - #3501
- [x] fetchmail - By @MiquelRForgeFlow - #3483
- [x] fetchmail_gmail - By @pedrobaeza - #4482
- [x] fetchmail_outlook - By @pedrobaeza - #3732
- [x] fleet - By @MiquelRForgeFlow - #3482
- [x] gamification - By @sang250399 - #3340
- [x] gamification_sale_crm - By @duong77476 - #3385
- [x] google_account - By @duong77476 - #3386
- [x] google_calendar - By @MiquelRForgeFlow - #3489
- [x] google_drive - By @duong77476 - #3408
- [x] google_gmail - By @pedrobaeza - #4480
- [x] google_recaptcha - By @MiquelRForgeFlow - #3488
- [x] google_spreadsheet - By @daonamutc1 - #3403
- [x] hr - By @MiquelRForgeFlow - #3481
- [x] hr_attendance - By @daonamutc1 - #3355
- [x] hr_contract - By @pedrobaeza / @sang250399 - #3688
- [x] hr_expense - By @pedrobaeza - #3689
- [x] hr_fleet - By @sang250399 - #3333
- [x] hr_gamification - By @duong77476 - #3410
- [x] hr_holidays - By @tranngocson1996 - #3336
- [x] hr_holidays_attendance - By @duong77476 - #3313
- [x] hr_maintenance - By @duong77476 - #3411
- [x] hr_org_chart - By @duong77476 - #3412
- [x] hr_presence - By @duong77476 - #3413
- [x] hr_recruitment - By @sang250399 - #3343
- [x] hr_recruitment_survey - By @duong77476 - #3414
- [x] hr_skills - By @daonamutc1 - #3402
- [x] hr_skills_slides - By @duong77476 - #3415
- [x] hr_skills_survey - By @duong77476 - #3416
- [x] hr_timesheet - By @sang250399 - #3306
- [x] hr_timesheet_attendance - By @duong77476 - #3417
- [x] http_routing - By @MiquelRForgeFlow - #3462
- [x] iap - By @daonamutc1 - #3392
- [x] iap_crm - By @MiquelRForgeFlow - #3503
- [x] iap_mail - By @duong77476 - #3420
- [x] im_livechat - By @daonamutc1 - #3361
- [x] im_livechat_mail_bot - By @duong77476 - #3421
- [x] l10n_ar - By @pedrobaeza - #4208
- [x] l10n_be - By @pedrobaeza - #4210
- [x] l10n_co - By @pedrobaeza - #4407
- [x] l10n_de - By @pedrobaeza - #4988
- [x] l10n_de_skr04 - By @pedrobaeza - #4992
- [x] l10n_es - By @pedrobaeza - #3636
- [x] l10n_fr - By @pedrobaeza - #4483
- [x] l10n_fr_fec - By @pedrobaeza - #4484
- [x] l10n_latam_base - By @pedrobaeza - #4206
- [x] l10n_latam_invoice_document - By @pedrobaeza - #4207
- [x] l10n_ma - By @ernestotejeda - #3799
- [x] l10n_multilang - By @pedrobaeza - #4201
- [x] l10n_mx - By @pedrobaeza - #4405
- [x] l10n_pe - By @pedrobaeza - #4401
- [x] l10n_vn - By @tranngocson1996 - #3351
- [x] link_tracker - By @MiquelRForgeFlow - #3485
- [x] mail - By @sang250399 - #3273
- [x] mail_bot - By @MiquelRForgeFlow - #3465
- [x] mail_bot_hr - By @duong77476 - #3424
- [x] maintenance - By @sang250399 - #3281
- [x] mass_mailing - By @MiquelRForgeFlow - #3524
- [x] mass_mailing_crm - By @duong77476 - #3317
- [x] mass_mailing_event - By @MiquelRForgeFlow - #3737
- [x] mass_mailing_event_track - By @pedrobaeza - #4044
- [x] mass_mailing_sale - By @duong77476 - #3318
- [x] mass_mailing_slides - By @daonamutc1 - #3397
- [x] membership - By @duong77476 - #3426
- [x] microsoft_account - By @duong77476 - #3427
- [x] microsoft_calendar - By @MiquelRForgeFlow - #3486
- [x] microsoft_outlook - By @MiquelRForgeFlow - #3486
- [x] mrp - By @MiquelRForgeFlow - #3744
- [x] mrp_account - By @ernestotejeda - #3791
- [x] note - By @daonamutc1 - #3362
- [x] note_pad - By @duong77476 - #3423
- [x] pad - By @daonamutc1 - #3359
- [x] pad_project - By @duong77476 - #3429
- [x] partner_autocomplete - By @duong77476 - #3430
- [x] payment - By @MiquelRForgeFlow / @pedrobaeza - #3513
- [x] payment_adyen - By @MiquelRForgeFlow - #3514
- [x] payment_alipay - By @MiquelRForgeFlow - #3514
- [x] payment_authorize - By @MiquelRForgeFlow - #3514
- [x] payment_buckaroo - By @MiquelRForgeFlow - #3514
- [x] payment_mollie - By @MiquelRForgeFlow - #3514
- [x] payment_ogone - By @MiquelRForgeFlow - #3514
- [x] payment_paypal - By @MiquelRForgeFlow - #3514
- [x] payment_payulatam - By @MiquelRForgeFlow - #3514
- [x] payment_payumoney - By @MiquelRForgeFlow - #3514
- [x] payment_sips - By @MiquelRForgeFlow - #3514
- [x] payment_transfer - By @MiquelRForgeFlow - #3514
- [x] phone_validation - By @sang250399 - #3277
- [x] point_of_sale - By @MiquelRForgeFlow - #3542
- [x] portal - By @MiquelRForgeFlow - #3464
- [x] portal_rating - By @daonamutc1 - #3406
- [x] pos_discount - By @pedrobaeza - #4522
- [x] pos_epson_printer - By @pedrobaeza - #4516
- [x] pos_restaurant - By @legalsylvain - #4266
- [x] pos_sale - By @legalsylvain - #4267
- [x] procurement_jit - By @duong77476 - #3431
- [x] product - By @MiquelRForgeFlow - #3492
- [x] product_email_template - By @pedrobaeza - #4520
- [x] product_expiry - By @sergio-teruel - #3633
- [x] product_margin - By @daonamutc1 - #3391
- [x] product_matrix - By @daonamutc1 - #3390
- [x] project - By @MiquelRForgeFlow - #3491
- [x] project_timesheet_holidays - By @duong77476 - #3432
- [x] purchase - By @MiquelRForgeFlow - #3518
- [x] purchase_mrp - By @ernestotejeda - #3788
- [x] purchase_requisition - By @hieu1211 / @pedrobaeza - #3685
- [x] purchase_requisition_stock - By @hieu1211 - #3321
- [x] purchase_stock - By @hieu1211 - #3335
- [x] rating - By @hieu1211 - #3324
- [x] repair - By @carlos-lopez-tecnativa - #5047
- [x] resource - By @sang250399 - #3275
- [x] sale - By @MiquelRForgeFlow / @pedrobaeza - #3516
- [x] sale_coupon - By @daonamutc1 - #3364
- [x] sale_coupon_delivery - By @pedrobaeza - #3797
- [x] sale_crm - By @duong77476 - #3433
- [x] sale_expense - By @duong77476 - #3434
- [x] sale_management - By @MiquelRForgeFlow / @pedrobaeza - #3519
- [x] sale_margin - By @sergio-teruel - #3634
- [x] sale_mrp - By @ernestotejeda - #3787
- [x] sale_product_configurator - By @daonamutc1 - #3396
- [x] sale_product_matrix - By @daonamutc1 - #3393
- [x] sale_project - By @pedrobaeza - #3686
- [x] sale_purchase - By @duong77476 - #3436
- [x] sale_purchase_stock - By @pedrobaeza - #4490
- [x] sale_quotation_builder - By @duong77476 - #3437
- [x] sale_stock - By @MiquelRForgeFlow - #3531
- [x] sale_stock_margin - By @carlos-lopez-tecnativa - #5411
- [x] sale_timesheet - By @daonamutc1 / @pedrobaeza - #3690
- [x] sale_timesheet_edit - By @duong77476 - #3438
- [x] sale_timesheet_purchase - By @pedrobaeza - #3804
- [x] sales_team - By @MiquelRForgeFlow - #3487
- [x] sms - By @daonamutc1 - #3358
- [x] snailmail - By @daonamutc1 - #3356
- [x] snailmail_account - By @duong77476 - #3439
- [x] social_media - By @duong77476 - #3440
- [x] stock - By @MiquelRForgeFlow - #3510
- [x] stock_account - By @MiquelRForgeFlow - #3527
- [x] stock_dropshipping - By @pedrobaeza - #3753
- [x] stock_landed_costs - By @duong77476 - #3441
- [x] stock_sms - By @duong77476 - #3442
- [x] survey - By @sang250399 / @pedrobaeza - #3687
- [x] uom - By @sang250399 - #3267
- [x] utm - By @sang250399 - #3282
- [x] web - By @sang250399 - #3265
- [x] web_editor - By @MiquelRForgeFlow - #3479
- [x] web_kanban_gauge - By @duong77476 - #3444
- [x] web_tour - By @sang250399 - #3269
- [x] web_unsplash - By @hhgabelgaard - #3620
- [x] website - By @tranngocson1996 / @pedrobaeza - #3347
- [x] website_blog - By @duong77476 - #3445
- [x] website_crm - By @duong77476 - #3452
- [x] website_crm_livechat - By @duong77476 - #3452
- [x] website_crm_partner_assign - By @duong77476 - #3452
- [x] website_crm_sms - By @duong77476 - #3452
- [x] website_customer - By @duong77476 - #3453
- [x] website_event - By @MiquelRForgeFlow - #3738
- [x] website_event_crm - By @remytms - #4348
- [x] website_event_crm_questions - By @remytms - #4350
- [x] website_event_questions - By @pedrobaeza - #4038
- [x] website_event_sale - By @MiquelRForgeFlow - #3740
- [x] website_event_track - By @pedrobaeza - #3751
- [x] website_form - By @pedrobaeza - #3692
- [x] website_form_project - By @duongnguyen / @pedrobaeza - #3692
- [x] website_forum - By @daonamutc1 - #3394
- [x] website_google_map - By @ernestotejeda - #3792
- [x] website_hr_recruitment - By @MiquelRForgeFlow - #3739
- [x] website_links - By @sergio-teruel - #3642
- [x] website_livechat - By @daonamutc1 - #3405
- [x] website_mail - By @sergio-teruel - #3645
- [x] website_mass_mailing - By @sang250399 - #3310
- [x] website_membership - By @pedrobaeza - #4037
- [x] website_partner - By @CarlosRoca13 - #3574
- [x] website_payment - By @duong77476 - #3316
- [x] website_profile - By @sang250399 - #3307
- [x] website_sale - By @duong77476 / @pedrobaeza - #3693
- [x] website_sale_comparison - By @sergio-teruel - #3644
- [x] website_sale_coupon - By @pedrobaeza - #3796
- [x] website_sale_coupon_delivery - By @pilarvargas-tecnativa - #4526
- [x] website_sale_delivery - By @sergio-teruel - #3647
- [x] website_sale_digital - By @pedrobaeza - #4503
- [x] website_sale_product_configurator - By @pedrobaeza - #3800
- [x] website_sale_stock - By @sergio-teruel - #3725
- [x] website_sale_stock_product_configurator - By @pedrobaeza - #3801
- [x] website_sale_wishlist - By @daonamutc1 - #3395
- [x] website_slides - By @sang250399 - #3309
- [x] website_slides_forum - By @sang250399 - #3308
- [x] website_slides_survey - By @sang250399 - #3338
- [x] website_sms - By @MiquelRForgeFlow - #3741
- [x] website_twitter - By @pedrobaeza - #4045

**Comment by Robrechtc** [comment]
I have a dumb question and I'd rather not make a new issue for one question - if I want to upgrade an instance from v14 to v15 using the OpenUpgrade scripts, should I run Odoo v15 with an existing v14 database? I've looked through the docs but so far this is unclear

**Comment by legalsylvain** [comment]
Hi. Thanks for asking. 

Please :
- open a dedicated issue
- mention the part of the documentation that is unclear

regards.

**Comment by gdgellatly** [comment]
@legalsylvain I added the missing uom migration PR #3267 , which was merged, however it didn't update the issue with a checkbox. Not sure best thing to do.

EDIT: Also base and analytic are done but missing.

**Comment by legalsylvain** [comment]
Do you mean that the bot added the uom line, but not checked ?

**Comment by gdgellatly** [comment]
@legalsylvain sorry, missed this. Yes exactly what happened.

**Comment by legalsylvain** [comment]
That is normal. You can open an issue on https://github.com/OCA/oca-github-bot to ask improvment.

**Comment by pedrobaeza** [comment]
You already opened it, Sylvain! https://github.com/OCA/oca-github-bot/issues/189

**Comment by gdgellatly** [comment]
Well I was asking mainly because the issue now had incorrect information. Two missing modules and a not checked one and just asking what we need to do to resolve that.

**Comment by pedrobaeza** [comment]
Edit the main comment and amend what is incorrect according you.

**Comment by gdgellatly** [comment]
Thanks - done
