### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by legalsylvain** [OCA/OpenUpgrade#3681]
- Full list of modules available here : https://github.com/OCA/OpenUpgrade/blob/16.0/docsource/modules150-160.rst 

# Pending / done work

- [x] account - By @ngochung207 / @pedrobaeza - #4070
- [x] account_check_printing - By @CarlosRoca13 - #4909
- [x] account_debit_note - By @pedrobaeza - #4404
- [x] account_edi - By @remi-filament - #4300
- [x] account_edi_ubl - By @remi-filament - #4158
- [x] account_edi_ubl_cii - By @remi-filament - #4158
- [x] account_fleet - By @pedrobaeza - #4504
- [x] account_payment - By @remytms - #3920
- [x] account_qr_code_sepa - By @robinkeunen - #4337
- [x] account_sale_timesheet - By @MiquelRForgeFlow - #4721
- [x] analytic - By @duong77476-viindoo / @pedrobaeza - #4188
- [x] association - By @stefan-tecnativa - #4175
- [x] attachment_indexation - By @pedrobaeza - #4189
- [x] auth_ldap - By @marielejeune - #3776
- [x] auth_oauth - By @locdang8 - #4013
- [x] auth_password_policy - By @locdang8 - #3969
- [x] auth_password_policy_portal - By @locdang8 - #4000
- [x] auth_password_policy_signup - By @locdang8 - #4025
- [x] auth_signup - By @marielejeune - #3778
- [x] auth_totp - By @locdang8 - #4006
- [x] auth_totp_mail - By @pedrobaeza - #4365
- [x] auth_totp_portal - By @robinkeunen - #4338
- [x] barcode_gs1_nomenclature - By @locdang8 - #3934
- [x] barcodes - By @nguyenvietlam0640 - #3930
- [x] base - By @hbrunn - #3680
- [x] base_address_extended - By @marielejeune - #3769
- [x] base_automation - By @marielejeune - #3779
- [x] base_geolocalize - By @locdang8 - #4039
- [x] base_iban - By @remytms - #3870
- [x] base_import - By @marielejeune - #3772
- [x] base_setup - By @remytms - #3869
- [x] base_sparse_field - By @marielejeune - #3770
- [x] base_vat - By @remytms - #3871
- [x] board - By @remytms - #3900
- [x] bus - By @marielejeune - #3773
- [x] calendar - By @remytms - #3899
- [x] calendar_sms - By @SonCrits - #4034
- [x] contacts - By @remytms - #3897
- [x] crm - By @marielejeune - #3765
- [x] crm_iap_enrich - By @diamondnguyenkc - #3986
- [x] crm_iap_mine - By @diamondnguyenkc - #3988
- [x] crm_livechat - By @diamondnguyenkc - #3993
- [x] crm_mail_plugin - By @MiquelRForgeFlow - #4722
- [x] crm_sms - By @MiquelRForgeFlow - #4723
- [x] delivery - By @pedrobaeza - #4370
- [x] digest - By @marielejeune - #3783
- [x] event - By @marielejeune - #3767
- [x] event_booth - By @diamondnguyenkc - #3974
- [x] event_booth_sale - By @diamondnguyenkc - #3972
- [x] event_crm - By @diamondnguyenkc - #3976
- [x] event_sale - By @diamondnguyenkc - #3985
- [x] event_sms - By @diamondnguyenkc - #3977
- [x] fetchmail - By @huguesdk - #3963
- [x] fetchmail_gmail - By @duong77476 - #3992
- [x] fetchmail_outlook - By @pedrobaeza - #4496
- [x] fleet - By @nguyenvietlam0640 / @pedrobaeza - #3947
- [x] gamification - By @duyquyen96 - #3932
- [x] gamification_sale_crm - By @locdang8 - #4026
- [x] google_account - By @duong77476 - #4009
- [x] google_calendar - By @duong77476 - #4011
- [x] google_drive - By @duong77476 - #3998
- [x] google_gmail - By @duong77476 - #4018
- [x] google_recaptcha - By @duong77476 - #4040
- [x] google_spreadsheet - By @duong77476 - #4002
- [x] hr - By @remytms - #3911
- [x] hr_attendance - By @nguyenvietlam0640 - #3933
- [x] hr_contract - By @remytms / @pedrobaeza - #4336
- [x] hr_expense - By @victoralmau - #4156
- [x] hr_fleet - By @nguyenvietlam0640 - #3937
- [x] hr_gamification - By @nguyenvietlam0640 - #3987
- [x] hr_holidays - By @remytms / @pedrobaeza - #4335
- [x] hr_holidays_attendance - By @pedrobaeza - #4434
- [x] hr_hourly_cost - By @nguyenvietlam0640 - #3958
- [x] hr_maintenance - By @nguyenvietlam0640 - #3954
- [x] hr_org_chart - By @nguyenvietlam0640 - #3968
- [x] hr_presence - By @nguyenvietlam0640 - #4048
- [x] hr_recruitment - By @robinkeunen / @pedrobaeza - #4333
- [x] hr_recruitment_survey - By @nguyenvietlam0640 - #3995
- [x] hr_skills - By @pedrobaeza - #4435
- [x] hr_skills_slides - By @nguyenvietlam0640 - #4054
- [x] hr_skills_survey - By @nguyenvietlam0640 - #3967
- [x] hr_timesheet - By @nguyenvietlam0640 - #4029
- [x] hr_timesheet_attendance - By @nguyenvietlam0640 - #4046
- [x] hr_work_entry - By @victoralmau - #4170
- [x] hr_work_entry_contract - By @victoralmau - #4172
- [x] hr_work_entry_holidays - By @victoralmau - #4171
- [x] http_routing - By @huguesdk - #3964
- [x] iap - By @duyquyen96 - #3941
- [x] iap_crm - By @duyquyen96 - #3942
- [x] iap_mail - By @duong77476 - #3991
- [x] im_livechat - By @locdang8 - #3983
- [x] im_livechat_mail_bot - By @SonCrits - #4008
- [x] l10n_ar - By @pedrobaeza - #4453
- [x] l10n_be - By @remytms - #4304
- [x] l10n_co - By @pedrobaeza - #4408
- [x] l10n_de - By @pedrobaeza - #4989
- [x] l10n_de_skr04 - By @pedrobaeza - #4993
- [x] l10n_es - By @stefan-tecnativa - #4144
- [x] l10n_fr - By @legalsylvain - #4265
- [x] l10n_fr_fec - By @pedrobaeza - #4500
- [x] l10n_latam_base - By @pedrobaeza - #4409
- [x] l10n_latam_invoice_document - By @pedrobaeza - #4454
- [x] l10n_multilang - By @pedrobaeza - #4400
- [x] l10n_mx - By @pedrobaeza - #4406
- [x] l10n_pe - By @pedrobaeza - #4402
- [x] link_tracker - By @locdang8 - #3948
- [x] loyalty - By @pilarvargas-tecnativa - #4187
- [x] lunch - By @SonCrits - #3935
- [x] mail - By @marielejeune - #3832
- [x] mail_bot - By @locdang8 - #3952
- [x] mail_bot_hr - By @robinkeunen - #4339
- [x] mail_group - By @SonCrits - #4010
- [x] mail_plugin - By @locdang8 - #3997
- [x] maintenance - By @nguyenvietlam0640 - #3953
- [x] mass_mailing - By @locdang8 / @pedrobaeza - #4053
- [x] mass_mailing_crm - By @victoralmau - #4173
- [x] mass_mailing_event - By @pedrobaeza - #4198
- [x] mass_mailing_event_track - By @pedrobaeza - #4394
- [x] mass_mailing_sale - By @victoralmau - #4174
- [x] mass_mailing_slides - By @carlos-lopez-tecnativa - #4981
- [x] membership - By @SonCrits - #4007
- [x] microsoft_account - By @carlos-lopez-tecnativa - #5063
- [x] microsoft_calendar - By @carlos-lopez-tecnativa - #5064
- [x] microsoft_outlook - By @pedrobaeza - #4495
- [x] mrp - By @pedrobaeza - #4381
- [x] mrp_account - By @victoralmau - #4157
- [x] mrp_landed_costs - By @pedrobaeza - #4726
- [x] note - By @SonCrits - #3938
- [x] note_pad - By @duong77476 - #3981
- [x] pad - By @duong77476 - #3975
- [x] pad_project - By @duong77476 - #3982
- [x] partner_autocomplete - By @locdang8 - #3980
- [x] payment - By @remytms / @pedrobaeza - #4193
- [x] payment_custom - By @carmenbianca - #3965
- [x] payment_paypal - By @victoralmau - #4179
- [x] payment_stripe - By @victoralmau - #4178
- [x] payment_transfer - By @carmenbianca - #3965
- [x] phone_validation - By @marielejeune - #3780
- [x] point_of_sale - By @carmenbianca - #4392 / @pedrobaeza - #4417
- [x] portal - By @marielejeune - #3782
- [x] portal_rating - By @locdang8 - #3961
- [x] pos_discount - By @pedrobaeza - #4524
- [x] pos_epson_printer - By @pedrobaeza - #4517
- [x] pos_restaurant - By @legalsylvain - #4268
- [x] pos_sale - By @legalsylvain - #4269
- [x] product - By @remytms - #3880
- [x] product_email_template - By @pedrobaeza - #4523
- [x] product_expiry - By @victoralmau - #4136
- [x] product_margin - By @pedrobaeza - #4321
- [x] product_matrix - By @SonCrits - #4035
- [x] project - By @remytms - #4289
- [x] project_hr_expense - By @SonCrits - #3943
- [x] project_mrp - By @SonCrits - #3944
- [x] project_purchase - By @SonCrits - #3945
- [x] project_sms - By @SonCrits - #3956
- [x] project_timesheet_holidays - By @MiquelRForgeFlow - #4822
- [x] purchase - By @remi-filament - #4303
- [x] purchase_mrp - By @victoralmau - #4155
- [x] purchase_product_matrix - By @MiquelRForgeFlow - #4823
- [x] purchase_requisition - By @pedrobaeza - #4328
- [x] purchase_requisition_stock - By @hoangtiendung070797 - #4075
- [x] purchase_requisition_stock_dropshipping - By @MiquelRForgeFlow - #4739
- [x] purchase_stock - By @hoangtiendung070797 - #4067
- [x] rating - By @remytms - #3898
- [ ] repair - By @remi-filament - #4302
- [x] resource - By @marielejeune - #3784
- [x] sale - By @duong77476-viindoo / @pedrobaeza - #4301
- [x] sale_crm - By @diamondnguyenkc - #3996
- [x] sale_expense - By @robinkeunen / @pedrobaeza - #4411
- [x] sale_expense_margin - By @diamondnguyenkc - #4032
- [x] sale_loyalty - By @pilarvargas-tecnativa - #4212
- [x] sale_loyalty_delivery - By @pilarvargas-tecnativa - #4506
- [x] sale_management - By @huguesdk - #4014
- [x] sale_margin - By @diamondnguyenkc - #4027
- [x] sale_mrp - By @carmenbianca - #4116
- [x] sale_product_configurator - By @diamondnguyenkc - #4064
- [x] sale_product_matrix - By @diamondnguyenkc - #3999
- [x] sale_project - By @hoangtiendung070797 / @pedrobaeza - #4344
- [x] sale_project_stock - By @diamondnguyenkc - #4031
- [x] sale_purchase - By @huguesdk / @pedrobaeza - #4366
- [x] sale_purchase_stock - By @pedrobaeza - #4367
- [x] sale_quotation_builder - By @celm1990 - #4982
- [x] sale_stock - By @huguesdk - #4015
- [x] sale_stock_margin - By @hoangtiendung070797 - #4077
- [x] sale_timesheet - By @hoangtiendung070797 / @pedrobaeza - #4345
- [x] sale_timesheet_margin - By @MiquelRForgeFlow - #4720
- [x] sales_team - By @marielejeune  - #3781
- [x] sms - By @locdang8 - #4033
- [x] snailmail - By @locdang8 - #3984
- [x] social_media - By @duyquyen96 - #3940
- [x] stock - By @marielejeune - #4291
- [x] stock_account - By @robinkeunen - #4293
- [x] stock_dropshipping - By @victoralmau - #4135
- [x] stock_landed_costs - By @hoangtiendung070797 - #4071
- [x] stock_picking_batch - By @pedrobaeza - #4501
- [x] stock_sms - By @hoangtiendung070797 - #3970
- [x] survey - By @pedrobaeza - #4334
- [x] theme_default - By @pedrobaeza - #4368
- [x] uom - By @remytms - #3877
- [x] utm - By @marielejeune - #3774
- [x] web - By @marielejeune - #3771
- [x] web_editor - By @marielejeune - #3777
- [x] web_kanban_gauge - By @remytms - #3879
- [x] web_tour - By @marielejeune - #3775
- [x] web_unsplash - By @locdang8 - #4082
- [x] website - By @duyquyen96 - #3949
- [x] website_blog - By @locdang8 - #4074
- [x] website_crm - By @victoralmau - #4176
- [x] website_crm_livechat - By @pedrobaeza - #4364
- [x] website_crm_partner_assign - By @MiquelRForgeFlow - #4819
- [x] website_event - By @nguyenvietlam0640 - #4081
- [x] website_event_crm - By @remytms - #4347
- [x] website_event_crm_questions - By @remytms - #4349
- [x] website_event_questions - By @pedrobaeza - #4393
- [x] website_event_sale - By @nguyenvietlam0640 - #4089
- [x] website_event_track - By @nguyenvietlam0640 / @pedrobaeza - #4086
- [x] website_form_project - By @pedrobaeza - #4346
- [x] website_forum - By @nguyenvietlam0640 - #4087
- [x] website_google_map - By @duong77476 - #4041
- [x] website_hr_recruitment - By @nguyenvietlam0640 / @pedrobaeza - #4079
- [x] website_jitsi - By @locdang8 - #4076
- [x] website_links - By @locdang8 - #3990
- [x] website_livechat - By @locdang8 - #4024
- [x] website_mail - By @duyquyen96 - #4019
- [x] website_mail_group - By @duyquyen96 - #4021
- [x] website_mass_mailing - By @duyquyen96 - #4017
- [x] website_membership - By @duyquyen96 - #4022
- [x] website_partner - By @duyquyen96 - #4023
- [x] website_payment - By @victoralmau - #4185
- [x] website_profile - By @victoralmau / @pedrobaeza - #4177
- [x] website_sale - By @pedrobaeza - #4363
- [x] website_sale_comparison - By @victoralmau - #4137
- [x] website_sale_delivery - By @victoralmau - #4183
- [x] website_sale_digital - By @pedrobaeza - #4502
- [x] website_sale_loyalty - By @pilarvargas-tecnativa - #4226
- [x] website_sale_loyalty_delivery - By @pilarvargas-tecnativa - #4527
- [x] website_sale_product_configurator - By @victoralmau - #4138
- [x] website_sale_slides - By @carlos-lopez-tecnativa - #4979
- [x] website_sale_stock - By @victoralmau - #4182
- [x] website_sale_stock_product_configurator - By @pedrobaeza - #4369
- [x] website_sale_wishlist - By @victoralmau - #4181
- [x] website_slides - By @nguyenvietlam0640 / @pedrobaeza - #4056
- [x] website_slides_forum - By @pedrobaeza - #5051
- [x] website_slides_survey - By @carlos-lopez-tecnativa - #4980
- [x] website_twitter - By @diamondnguyenkc - #4065

**Comment by marielejeune** [comment]
Hi, 
Is there any reason why some modules are not present in `openupgrade_scripts/scripts`? For example `contacts`, `base_setup`, `http_routing` and `web_unsplash`?

**Comment by legalsylvain** [comment]
Hi @marielejeune. The scripts files (diff.txt + noupdate.xml) are generated by this module https://github.com/OCA/server-tools/tree/16.0/upgrade_analysis.

I don't know why the modules are missing. You can run this module if you want to investigate.
(note : if it's the first time, you have to run two instances 15 + 16 with upgrade_analysis installed on both, and then make the V16 communicate with the 15. It will create / update all the analysis).

kind regards.

**Comment by remytms** [comment]
@legalsylvain I've run again the upgrade_analysis module, with a database with `base_setup` installed. It creates the analysis files for `base`, and other module, but not for `base_setup`. Currently I don't know why.

Is the generation of the analysis file a requirement for writing migration scripts for this module in the OCA process ?

**Comment by legalsylvain** [comment]
Hi.
1) I think it's more a topic related to https://github.com/OCA/server-tools/tree/16.0/upgrade_analysis
2) Yes I saw that sometimes, there is no analysis file, and sometimes, there is an analysis file with minimal text. (nothing to do in the three part). But I don't know why. 

> Is the generation of the analysis file a requirement for writing migration scripts for this module in the OCA process ?

No. But if there is no file, I think that there is nothing to do.
But you can write a pre- / post- migration file if you see that some scripts are required.

**Comment by legalsylvain** [comment]
Hi all. 
FYI, changes on account.tag will be done on 16.0 "stable" version. See : https://github.com/OCA/account-analytic/issues/551#issuecomment-1561224426 

I guess that once done, we should regenerate analysis.txt file.

CC : @OCA/openupgrade-maintainers

**Comment by pedrobaeza** [comment]
Let's see first how it's handled. Not sure the path they are going to take. I suppose they are going to create an extra module for restoring the missing models and defaults, but it's just a theory.

**Comment by daiduongnguyen-odoo** [comment]
> Hi all. FYI, changes on account.tag will be done on 16.0 "stable" version. See : [OCA/account-analytic#551 (comment)](https://github.com/OCA/account-analytic/issues/551#issuecomment-1561224426)
> 
> I guess that once done, we should regenerate analysis.txt file.
> 
> CC : @OCA/openupgrade-maintainers

Are you going to regenerate the analyst fiels soon, i see some of them are outdated (eg: analytic)

**Comment by legalsylvain** [comment]
Hi @duong77476. 

Thanks for your all your recent contribution.

> Are you going to regenerate the analyst fiels soon, i see some of them are outdated (eg: analytic)

Could you try to do a PR on this subject? 
Basically, it's about playing with 2 instances of odoo. (15 and 16) with the upgrade_analysis module installed.

See : https://github.com/OCA/server-tools/tree/16.0/upgrade_analysis#upgrade-analysis

Let me know if you have questions !

**Comment by daiduongnguyen-odoo** [comment]
@legalsylvain Sure no problem, i have run it before back in Odoo 15 Migration

**Comment by mostafabarmshory** [comment]
How could I check if account migration is done? can any one help?

**Comment by legalsylvain** [comment]
> How could I check if account migration is done? can any one help?

Hi. account (and analytic) migration PR are referenced in this issue. 
You can review it and give feedback. 

thanks !

**Comment by mholthausen** [comment]
Is there any reason that `ir_*` modules aren't listed here? Every time I run the migration script, some fields of theses tables aren't migrated (conversion into `jsonb` fields is missing in some of them)

**Comment by pedrobaeza** [comment]
They are not modules, but models. If there's anything missing, specify in a new issue exactly the fields.

**Comment by MuhammadFayyazq125** [comment]
Hi, I am unable to view my account.move.line and chart of account types records in views but data exist in database. Please help me out to resolve this issue as i did everything possibilities but couldn't retrieve it in views.

**Comment by marielejeune** [comment]
Hi, I've opened a new PR to finish (I hope) the migration scripts for `stock` module: https://github.com/OCA/OpenUpgrade/pull/4291

**Comment by robinkeunen** [comment]
Hi, I see `account_qr_code_sepa` in the module list at _module150-160.rst_ but not in the list above nor in `openupgrade_scripts` directory. Is there something I should do to add it ?

Same question for `auth_totp_portal`.

EDIT: I see the diffs are empty => marking them as done.

**Comment by legalsylvain** [comment]
> not in the list above

this is the list of all the merged / pending PR.

> EDIT: I see the diffs are empty => marking them as done.

yes. could you make a PR ?

**Comment by parsonli** [comment]
Hi, after I upgraded to 16. I found out all of translations are lost. 
more specific, product name and product attribute has only one languages now.
Is this a normal thing or my database error thing?

**Comment by daiduongnguyen-odoo** [comment]
> Hi, after I upgraded to 16. I found out all of translations are lost. more specific, product name and product attribute has only one languages now. Is this a normal thing or my database error thing?

Probably a bug, my company struggling in migrate translation for html field (callable translation) and it's not perfect but still ok. For product name i'm not sure my company has same issue but no one say anything so i guest it fine. 
FYI, the translation migration we use is different compare to this openupgrade :v

**Comment by legalsylvain** [comment]
> Hi, after I upgraded to 16. I found out all of translations are lost. more specific, product name and product attribute has only one languages now. Is this a normal thing or my database error thing?

hi please open a dedicated issue. This issue is to enumerate pending work. Thanks
