### ISSUE TITLE
Migration to version 18.0

### ISSUE THREAD

**Issue by legalsylvain** [OCA/OpenUpgrade#4519]
Full list of modules available here : https://github.com/OCA/OpenUpgrade/blob/18.0/docsource/modules170-180.rst 

# Pending / done work

- [x] account - By @MiquelRForgeFlow - #4931
- [x] account_check_printing - By @carlos-lopez-tecnativa - #5424
- [x] account_debit_note - By @carlos-lopez-tecnativa - #5419
- [x] account_edi - By @remi-filament - #5093
- [x] account_edi_ubl_cii - By @pedrobaeza - #5143
- [x] account_edi_ubl_cii_tax_extension - By @MiquelRForgeFlow - #5175
- [x] account_fleet - By @PauMAVA - #5324
- [x] account_payment - By @MiquelRForgeFlow - #5005
- [x] account_qr_code_sepa - By @MiquelRForgeFlow - #5617
- [x] analytic - By @hbrunn - #4841
- [x] attachment_indexation - By @remi-filament - #5096
- [x] auth_ldap - By @carlos-lopez-tecnativa - #5418
- [x] auth_oauth - By @remi-filament - #5095
- [x] auth_password_policy - By @carlos-lopez-tecnativa - #5295
- [x] auth_password_policy_signup - By @carlos-lopez-tecnativa - #5296
- [x] auth_signup - By @MiquelRForgeFlow - #4947
- [x] auth_totp - By @MiquelRForgeFlow - #5002
- [x] auth_totp_mail - By @MiquelRForgeFlow - #5160
- [x] auth_totp_portal - By @pedrobaeza - #5135
- [x] barcodes - By @MiquelRForgeFlow - #4951
- [x] barcodes_gs1_nomenclature - By @MiquelRForgeFlow - #4951
- [x] base - By @hbrunn - #4709
- [x] base_address_extended - By @pedrobaeza - #5137
- [x] base_automation - By @pedrobaeza - #5207
- [x] base_geolocalize - By @MiquelRForgeFlow - #5279
- [x] base_iban - By @MiquelRForgeFlow - #5081
- [x] base_import - By @MiquelRForgeFlow - #5003
- [x] base_import_module - By @MiquelRForgeFlow - #5003
- [x] base_install_request - By @MiquelRForgeFlow - #5617
- [x] base_setup - By @hbrunn - #4740
- [x] base_sparse_field - By @pedrobaeza - #5139
- [x] base_vat - By @MiquelRForgeFlow - #5080
- [x] board - By @pedrobaeza - #5138
- [x] bus - By @hbrunn - #4742
- [x] calendar - By @MiquelRForgeFlow - #4969
- [x] calendar_sms - By @MiquelRForgeFlow - #5173
- [x] contacts - By @carlos-lopez-tecnativa - #4976
- [x] crm - By @BhaveshHeliconia - #5015
- [x] crm_iap_enrich - By @PauMAVA - #5225
- [x] crm_iap_mine - By @PauMAVA - #5225
- [x] crm_livechat - By @carlos-lopez-tecnativa - #5334
- [x] crm_sms - By @MiquelRForgeFlow - #5173
- [x] delivery - By @pedrobaeza - #5141
- [x] digest - By @MiquelRForgeFlow - #4950
- [x] event - By @BhaveshHeliconia / @MiquelRForgeFlow - #5049
- [x] event_product - By @pedrobaeza - #5128
- [x] event_sale - By @pedrobaeza - #5129
- [x] event_sms - By @MiquelRForgeFlow - #5173
- [x] fleet - By @jguenat - #5310
- [x] gamification - By @MiquelRForgeFlow - #5039
- [x] gamification_sale_crm - By @BhaveshHeliconia - #5030
- [x] google_account - By @carlos-lopez-tecnativa - #5231
- [x] google_calendar - By @carlos-lopez-tecnativa - #5232
- [x] google_gmail - By @MiquelRForgeFlow - #5160
- [x] google_recaptcha - By @MiquelRForgeFlow - #5183
- [x] hr - By @MiquelRForgeFlow - #5082
- [x] hr_attendance - By @MiquelRForgeFlow - #5255
- [x] hr_calendar - By @MiquelRForgeFlow - #5277
- [x] hr_contract - By @pedrobaeza - #5181
- [x] hr_expense - By @pedrobaeza - #5130
- [x] hr_fleet - By @PauMAVA - #5323
- [x] hr_gamification - By @BhaveshHeliconia - #5027
- [x] hr_holidays - By @MiquelRForgeFlow - #5260
- [x] hr_holidays_attendance - By @BhaveshHeliconia - #5025
- [x] hr_hourly_cost - By @MiquelRForgeFlow - #5223
- [x] hr_maintenance - By @carlos-lopez-tecnativa - #5238
- [x] hr_org_chart - By @pedrobaeza - #5140
- [x] hr_recruitment - By @MiquelRForgeFlow - #5275
- [x] hr_recruitment_skills - By @carlos-lopez-tecnativa - #5302
- [x] hr_recruitment_survey - By @carlos-lopez-tecnativa - #5294
- [x] hr_skills - By @pedrobaeza - #5180
- [x] hr_skills_slides - By @pedrobaeza - #5212
- [x] hr_skills_survey - By @carlos-lopez-tecnativa - #5241
- [x] hr_timesheet - By @remi-filament - #5101
- [x] hr_timesheet_attendance - By @carlos-lopez-tecnativa - #5237
- [x] hr_work_entry - By @BhaveshHeliconia - #5020
- [x] html_editor - By @hbrunn - #4743
- [x] http_routing - By @MiquelRForgeFlow - #4946
- [x] iap - By @MiquelRForgeFlow - #5001
- [x] iap_crm - By @PauMAVA - #5224
- [x] iap_mail - By @hbrunn - #5056
- [x] im_livechat - By @MiquelRForgeFlow - #5161
- [x] im_livechat_mail_bot - By @MiquelRForgeFlow - #5161
- [x] l10n_be - By @pedrobaeza - #5452
- [x] l10n_co - By @david-banon-tecnativa - #5538
- [x] l10n_dk - By @MiquelRForgeFlow - #5182
- [x] l10n_latam_base - By @carlos-lopez-tecnativa - #5420
- [x] l10n_latam_invoice_document - By @carlos-lopez-tecnativa - #5421
- [x] l10n_mx - By @david-banon-tecnativa - #5536
- [ ] l10n_pe - By @david-banon-tecnativa - #5537
- [x] l10n_pt - By @pedrobaeza - #5479
- [x] l10n_us - By @MiquelRForgeFlow - #5170
- [x] link_tracker - By @MiquelRForgeFlow - #5160
- [x] l10n_es - By @MiquelRForgeFlow - #5073
- [x] l10n_fr - By @remi-filament - #5090
- [x] l10n_fr_account - By @remi-filament - #5090
- [x] l10n_fr_fec - By @remi-filament - #5090
- [x] loyalty - By @MiquelRForgeFlow - #5252
- [x] mail - By @hbrunn - #4832
- [x] mail_bot - By @MiquelRForgeFlow - #5160
- [x] mail_bot_hr - By @MiquelRForgeFlow - #5160
- [x] mail_group - By @MiquelRForgeFlow - #5160
- [x] maintenance - By @MiquelRForgeFlow - #5162
- [x] mass_mailing - By @MiquelRForgeFlow - #5193
- [x] mass_mailing_crm - By @MiquelRForgeFlow - #5201
- [x] mass_mailing_crm_sms - By @MiquelRForgeFlow - #5201
- [x] mass_mailing_event - By @MiquelRForgeFlow - #5201
- [x] mass_mailing_event_sms - By @MiquelRForgeFlow - #5201
- [x] mass_mailing_event_track - By @carlos-lopez-tecnativa - #5422
- [x] mass_mailing_sale - By @MiquelRForgeFlow - #5201
- [x] mass_mailing_sale_sms - By @MiquelRForgeFlow - #5201
- [x] mass_mailing_slides - By @pedrobaeza - #5213
- [x] mass_mailing_sms - By @MiquelRForgeFlow - #5201
- [x] mass_mailing_themes - By @MiquelRForgeFlow - #5201
- [x] membership - By @MiquelRForgeFlow - #5202
- [x] microsoft_account - By @PauMAVA - #5226
- [x] microsoft_calendar - By @PauMAVA - #5264
- [x] microsoft_outlook - By @PauMAVA - #5226
- [x] mrp - By @hbrunn - #5092
- [x] mrp_account - By @hbrunn - #5114
- [x] mrp_landed_costs - By @pedrobaeza - #5402
- [x] mrp_product_expiry - By @jcmontoyadev - #5595
- [x] onboarding - By @MiquelRForgeFlow - #4944
- [x] partner_autocomplete - By @hbrunn - #5057
- [x] payment - By @MiquelRForgeFlow - #4958
- [x] payment_adyen - By @MiquelRForgeFlow - #5200
- [x] payment_custom - By @pedrobaeza - #5136
- [x] payment_paypal - By @MiquelRForgeFlow - #5198
- [x] payment_stripe - By @MiquelRForgeFlow - #5197
- [x] payment_worldline - By @MiquelRForgeFlow - #5490
- [x] phone_validation - By @MiquelRForgeFlow - #4999
- [x] point_of_sale - By @MiquelRForgeFlow - #5104
- [x] portal - By @MiquelRForgeFlow - #4949
- [x] portal_rating - By @pedrobaeza - #5188
- [x] pos_discount - By @david-banon-tecnativa - #5515
- [x] pos_epson_printer - By @carlos-lopez-tecnativa - #5317
- [x] pos_hr - By @carlos-lopez-tecnativa - #5307
- [x] pos_hr_restaurant - By @carlos-lopez-tecnativa - #5321
- [x] pos_mrp - By @MiquelRForgeFlow - #5172
- [x] pos_restaurant - By @carlos-lopez-tecnativa - #5320
- [x] pos_sale - By @MiquelRForgeFlow - #5174
- [x] pos_sms - By @MiquelRForgeFlow - #5173
- [x] privacy_lookup - By @MiquelRForgeFlow - #5160
- [x] product - By @hbrunn - #4839
- [x] product_email_template - By @david-banon-tecnativa - #5513
- [x] product_margin - By @MiquelRForgeFlow - #5253
- [x] project - By @MiquelRForgeFlow - #5203
- [x] project_account - By @BhaveshHeliconia - #5037
- [x] project_hr_expense - By @BhaveshHeliconia - #5038
- [x] project_mrp - By @MiquelRForgeFlow - #5251
- [x] project_mrp_account - By @MiquelRForgeFlow - #5251
- [x] project_mrp_sale - By @MiquelRForgeFlow - #5251
- [x] project_purchase - By @MiquelRForgeFlow - #5251
- [x] project_purchase_stock - By @MiquelRForgeFlow - #5251
- [x] project_sale_expense - By @MiquelRForgeFlow - #5617
- [x] project_sms - By @MiquelRForgeFlow - #5251
- [x] project_stock - By @MiquelRForgeFlow - #5251
- [x] project_stock_account - By @MiquelRForgeFlow - #5251
- [x] project_timesheet_holidays - By @MiquelRForgeFlow - #5276
- [x] project_todo - By @carlos-lopez-tecnativa - #5230
- [x] purchase - By @MiquelRForgeFlow - #5075
- [x] purchase_edi_ubl_bis3 - By @MiquelRForgeFlow - #5175
- [x] purchase_mrp - By @MiquelRForgeFlow - #5172
- [x] purchase_requisition - By @carlos-lopez-tecnativa - #5261
- [x] purchase_requisition_stock - By @carlos-lopez-tecnativa - #5263
- [x] purchase_stock - By @MiquelRForgeFlow - #5089
- [x] rating - By @MiquelRForgeFlow - #5061
- [x] repair - By @MiquelRForgeFlow - #5196
- [x] resource - By @MiquelRForgeFlow - #4945
- [x] resource_mail - By @MiquelRForgeFlow - #5060
- [x] sale - By @MiquelRForgeFlow - #5071
- [x] sale_async_emails - By @david-banon-tecnativa - #5510
- [x] sale_crm - By @BhaveshHeliconia - #5045
- [x] sale_edi_ubl - By @MiquelRForgeFlow - #5175
- [x] sale_expense - By @carlos-lopez-tecnativa - #5234
- [x] sale_loyalty - By @pilarvargas-tecnativa - #5270
- [x] sale_loyalty_delivery - By @pilarvargas-tecnativa - #5272
- [x] sale_management - By @remi-filament - #5099
- [x] sale_margin - By @carlos-lopez-tecnativa - #5233
- [x] sale_mrp - By @MiquelRForgeFlow - #5172
- [x] sale_pdf_quote_builder - By @MiquelRForgeFlow - #5176
- [x] sale_product_configurator - By @carlos-lopez-tecnativa - #5423
- [x] sale_project - By @remi-filament - #5100
- [x] sale_project_stock - By @MiquelRForgeFlow - #5617
- [x] sale_purchase - By @MiquelRForgeFlow - #5123
- [x] sale_purchase_stock - By @MiquelRForgeFlow - #5125
- [x] sale_service - By @MiquelRForgeFlow - #5222
- [x] sale_sms - By @MiquelRForgeFlow - #5173
- [x] sale_stock - By @MiquelRForgeFlow - #5083
- [x] sale_stock_margin - By @carlos-lopez-tecnativa - #5332
- [x] sale_timesheet - By @carlos-lopez-tecnativa - #5236
- [x] sales_team - By @MiquelRForgeFlow - #4967
- [x] sms - By @hbrunn - #5055
- [x] snailmail - By @hbrunn - #5056
- [x] snailmail_account - By @MiquelRForgeFlow - #5164
- [x] social_media - By @MiquelRForgeFlow - #5183
- [x] spreadsheet - By @MiquelRForgeFlow - #4968
- [x] spreadsheet_account - By @pedrobaeza - #5132
- [x] spreadsheet_dashboard - By @pedrobaeza - #5131
- [x] spreadsheet_dashboard_account - By @pedrobaeza - #5133
- [x] spreadsheet_dashboard_event_sale - By @pedrobaeza - #5451
- [x] spreadsheet_dashboard_hr_expense - By @pedrobaeza - #5362
- [x] spreadsheet_dashboard_hr_timesheet - By @PauMAVA - #5221
- [x] spreadsheet_dashboard_im_livechat - By @pedrobaeza - #5352
- [x] spreadsheet_dashboard_pos_hr - By @pedrobaeza - #5455
- [x] spreadsheet_dashboard_sale - By @pedrobaeza - #5134
- [x] spreadsheet_dashboard_sale_timesheet - By @PauMAVA - #5221
- [x] spreadsheet_dashboard_stock_account - By @MiquelRForgeFlow - #5171
- [x] stock - By @MiquelRForgeFlow - #4957
- [x] stock_account - By @MiquelRForgeFlow - #5072
- [x] stock_delivery - By @pedrobaeza - #5401
- [x] stock_dropshipping - By @pedrobaeza - #5142
- [x] stock_landed_costs - By @carlos-lopez-tecnativa - #5258
- [x] stock_picking_batch - By @carlos-lopez-tecnativa - #5262
- [x] stock_sms - By @MiquelRForgeFlow - #5173
- [x] survey - By @remi-filament - #5102
- [x] theme_default - By @pedrobaeza - #5350
- [x] uom - By @MiquelRForgeFlow - #4876
- [x] utm - By @MiquelRForgeFlow - #4875
- [x] web - By @hbrunn - #4741
- [x] web_editor - By @MiquelRForgeFlow - #4948
- [x] web_hierarchy - By @remi-filament - #5097
- [x] web_tour - By @hbrunn - #4744
- [x] web_unsplash - By @MiquelRForgeFlow - #5000
- [x] website - By @MiquelRForgeFlow - #5183
- [x] website_blog - By @carlos-lopez-tecnativa - #5249
- [x] website_crm - By @pedrobaeza - #5208
- [x] website_crm_livechat - By @carlos-lopez-tecnativa - #5333
- [x] website_crm_sms - By @MiquelRForgeFlow - #5280
- [x] website_event - By @MiquelRForgeFlow - #5278
- [x] website_event_jitsi - By @MiquelRForgeFlow - #5278
- [x] website_event_sale - By @MiquelRForgeFlow - #5278
- [x] website_event_track - By @carlos-lopez-tecnativa - #5335
- [x] website_forum - By @carlos-lopez-tecnativa - #5348
- [x] website_google_map - By @MiquelRForgeFlow - #5279
- [x] website_hr_recruitment - By @MiquelRForgeFlow - #5275
- [x] website_jitsi - By @MiquelRForgeFlow - #5278
- [x] website_links - By @pedrobaeza - #5185
- [x] website_livechat - By @carlos-lopez-tecnativa - #5246
- [x] website_mail - By @pedrobaeza - #5187
- [x] website_mail_group - By @MiquelRForgeFlow - #5279
- [x] website_mass_mailing - By @MiquelRForgeFlow - #5279
- [x] website_mass_mailing_sms - By @MiquelRForgeFlow - #5279
- [x] website_membership - By @MiquelRForgeFlow - #5279
- [x] website_partner - By @pedrobaeza - #5186
- [x] website_payment - By @pedrobaeza - #5214
- [x] website_profile - By @pedrobaeza - #5209
- [x] website_project - By @carlos-lopez-tecnativa - #5257
- [x] website_sale - By @pedrobaeza - #5217
- [x] website_sale_collect - By @carlos-lopez-tecnativa - #5349
- [x] website_sale_comparison - By @carlos-lopez-tecnativa - #5248
- [x] website_sale_loyalty - By @pilarvargas-tecnativa - #5271
- [x] website_sale_product_configurator - By @MiquelRForgeFlow - #4883
- [x] website_sale_stock - By @carlos-lopez-tecnativa - #5245
- [x] website_sale_wishlist - By @carlos-lopez-tecnativa - #5247
- [x] website_slides - By @pedrobaeza - #5211
- [x] website_slides_survey - By @carlos-lopez-tecnativa - #5256
- [x] website_sms - By @MiquelRForgeFlow - #5279

**Merged modules**

* [l10n-france/l10n_fr_pos_cert_update_draft_order_line](https://github.com/OCA/l10n-france/tree/16.0/l10n_fr_pos_cert_update_draft_order_line) : merged into l10n_fr_pos_cert : see https://github.com/odoo/odoo/pull/170140

**Comment by hbrunn** [comment]
I've worked on openupgrade_framework and the base module today, will probably push something testable next week.

I'm also looking into generating the analysis files automatically in a cronjob so that we always have the latest analysis on github without human intervention.

**Comment by legalsylvain** [comment]
> I've worked on openupgrade_framework and the base module today, will probably push something testable next week.

Nice ! I added a Version column in the main followup document.

> I'm also looking into generating the analysis files automatically in a cronjob so that we always have the latest analysis on github without human intervention.

interested. Created a dedicated issue to talk about that : https://github.com/OCA/OpenUpgrade/issues/4707

**Comment by chmuche** [comment]
Hello,

Thank you for your work.
One of our customers in Community Edition wants to migrate to v18.
We use only `account` + `l10n_fr` and `uom`. 

Do you have an estimate date of release v18 script for these 2 modules?

I don't know the governance in this repository.

Only `account` seems to have big changes (after looking is the analysis #4740)
Thanks

**Comment by hbrunn** [comment]
you can start contributing by reviewing the existing open PRs for v18, which are all prerequisites for the account migration

**Comment by hbrunn** [comment]
@OCA/openupgrade-maintainers given this is pretty mature by now, should we shift the default branch to 18.0?

**Comment by pedrobaeza** [comment]
Yes!

**Comment by yoanyr** [comment]
Hi everyone,

I’m migrating from Odoo v17 to v18 for the first time, and I’m encountering the following error:

```
odoo.tools.convert.ParseError: while parsing /temp/odoo/addons/partner_autocomplete/views/res_partner_views.xml:3
Error while validating view near:

<form string="Partners" __validate__="1">
                <div class="alert alert-warning oe_edit_only" role="alert" name="warning_tax" invisible="not same_vat_partner_id">
                  A partner with the same <span><field name="vat_label"/>
                <field name="partner_gid" invisible="True"/>

Field "team_id" does not exist in model "res.partner"

View error context:
{'file': '/temp/odoo/addons/partner_autocomplete/views/res_partner_views.xml',
 'line': 2,
 'name': 'res.partner.form.inherit.partner.autocomplete',
 'view': ir.ui.view(497,),
 'view.model': 'res.partner',
 'view.parent': ir.ui.view(128,),
 'xmlid': 'view_res_partner_form_inherit_partner_autocomplete'}

``` 
From what I can tell, this issue seems to occur because the team_id field was removed from the res.partner model in Odoo 18, but it’s still being referenced in one of the CRM or partner views.

Could someone please guide me on the proper way to resolve this issue in v18? Should I remove the field reference entirely, or replace it with a different field?

Thanks in advance for your help!
