### ISSUE TITLE
Dropping wiki

### ISSUE THREAD

**Issue by legalsylvain** [OCA/OpenUpgrade#4574]
Hi @OCA/openupgrade-maintainers 

As explained in this PR, I think the [current wiki](https://github.com/OCA/OpenUpgrade/wiki) should be dropped as it is very obsolete and not visible.

So far,

- [x] I created a backup of the current wiki. (readonly) https://github.com/grap/openupgrade_wiki_backup 
- [x] Dropped the following page, in the OpenUpgrade wiki:
    - [Migration-from-7.0-to-8.0.md](https://github.com/grap/openupgrade_wiki_backup/blob/master/Migration-from-7.0-to-8.0.md)
    - [Migration-from-Launchpad-to-Github-of-7.0-branch.md](https://github.com/grap/openupgrade_wiki_backup/blob/master/Migration-from-Launchpad-to-Github-of-7.0-branch.md)
    - [Planned migrations.textile](https://github.com/grap/openupgrade_wiki_backup/blob/master/Planned%20migrations.textile)
    - [Set-up-the-branch-for-a-new-Odoo-release.md](https://github.com/grap/openupgrade_wiki_backup/blob/master/Set-up-the-branch-for-a-new-Odoo-release.md)

**Pending Work**
- [ ] [How-to-create-a-reference-database.md](https://github.com/grap/openupgrade_wiki_backup/blob/master/How-to-create-a-reference-database.md) : https://github.com/OCA/OpenUpgrade/pull/4575

**Todo / Remaining work** 

Move into OCA/OpenUpgrade Documentation branch :

- [ ] [Crude-script-to-create-the-full-analysis-between-two-versions-of-Odoo.md](https://github.com/grap/openupgrade_wiki_backup/blob/master/Crude-script-to-create-the-full-analysis-between-two-versions-of-Odoo.md)
