### ISSUE TITLE
Migration scripts for v10

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/OpenUpgrade#757]
Issue for gathering all the required things for migrating to v10.

For this version, OCA has funded the development of the migration scripts that are installed in their Odoo instance. They are marked as `(OCA project)` for being recognized and expect them to be done in the near future if not yet done.

Odoo modules
-----------

- [x] account (OCA project) - By @NL66278 - #843
- [x] account_accountant (OCA project) - By @reinka - #868
- [x] account_analytic_default - By @reinka - #859 
- [x] account_asset - By @cubells - #839 
- [x] account_bank_statement_import 
- [x] account_budget - By @rruebner - #878
- [x] account_cancel (OCA project) - By @reinka - #870 - Nothing to do
- [x] account_check_printing - Nothing to do
- [ ] account_extra_reports 
- [x] account_full_reconcile - Merged in account
- [ ] account_tax_adjustments 
- [x] account_tax_cash_basis - By @rruebner - #881 - Nothing to do
- [ ] account_tax_exigible
- [x] account_tax_python - By @rruebner - #882 - Nothing to do
- [x] account_test - Nothing to do
- [x] account_voucher (OCA project) - By @mreficent - #845 
- [x] analytic (OCA project) - By @gfcapalbo - #802
- [x] anonymization - By @rruebner - #883 - Nothing to do
- [x] association (OCA project) - By @rruebner - #885  - Nothing to do
- [x] auth_crypt (OCA project) - By @rruebner - #886  - Nothing to do
- [x] auth_ldap - By @rruebner - #886   - Nothing to do
- [x] auth_oauth (OCA project) - By @rruebner - #886  - Nothing to do
- [x] auth_signup (OCA project) - Nothing to do
- [x] barcodes - By @astirpe - #865   - Nothing to do
- [x] base (OCA project) - By @hbrunn - #789 
- [x] base_action_rule (OCA project) - By @pedrobaeza - #801 
- [x] base_gengo - By @mreficent - #975 
- [x] base_geolocalize (OCA project) - Nothing to do
- [x] base_iban (OCA project) - By @reinka - #873  - Nothing to do
- [x] base_import (OCA project) - Nothing to do
- [ ] base_import_module
- [x] base_setup (OCA project) - By @pedrobaeza - #796 
- [x] base_vat (OCA project)  - By @reinka #864 - Nothing to do
- [x] board (OCA project) - By @reinka - #867 
- [x] bus (OCA project) - Nothing to do
- [x] calendar (OCA project) - By @pedrobaeza - #822 
- [ ] claim_from_delivery 
- [x] contacts - By @rruebner - #876 - Nothing to do
- [x] crm (OCA project) - By @pedrobaeza - #828
- [x] crm_claim (Deleted module) - Now hosted in https://github.com/OCA/crm/tree/10.0/crm_claim
- [ ] crm_partner_assign
- [x] crm_project_issue - By @pedrobaeza - #989
- [x] decimal_precision (OCA project) - Nothing to do
- [x] delivery - By @rruebner - #869
- [x] document (OCA project) - By @reinka - #874 - Nothing to do
- [x] event (OCA project) - By @mreficent - #889  - Nothing to do
- [x] event_sale (OCA project) - By @mreficent - #889  - Nothing to do
- [x] fetchmail (OCA project) - Nothing to do
- [x] fleet - By @archetipo - #1206 
- [ ] gamification
- [ ] gamification_sale_crm 
- [x] google_account - By @cubells - #1393 
- [x] google_calendar - By @cubells - #1396 
- [x] google_drive - Nothing to do
- [x] google_spreadsheet - By @cubells - #1395 
- [x] hr (OCA project) - By @astirpe - #849 
- [x] hr_attendance - By @pedrobaeza - #1003 
- [x] hr_contract - By @hbrunn - #897 - Nothing to do
- [ ] hr_equipment
- [x] hr_expense - By @cubells - #1130 
- [ ] hr_gamification 
- [x] hr_holidays - By @astirpe - #858
- [ ] hr_maintenance
- [ ] hr_payroll
- [ ] hr_payroll_account
- [x] hr_recruitment - By @pedrobaeza - #998
- [x] hr_recruitment_survey (new) - By @pedrobaeza - #998
- [x] hr_timesheet - By @pedrobaeza - #944
- [ ] hr_timesheet_attendance
- [x] hr_timesheet_sheet - By @pedrobaeza - #945
- [ ] hw_blackbox_be
- [ ] hw_escpos 
- [ ] hw_posbox_homepage
- [ ] hw_posbox_upgrade 
- [ ] hw_proxy
- [ ] hw_scale
- [ ] hw_scanner
- [x] im_livechat (OCA project) - By @mreficent - #973 
- [x] im_odoo_support  (deleted) - Merged in im_livechat
- [ ] l10n_ae 
- [ ] l10n_ar 
- [ ] l10n_at 
- [ ] l10n_au 
- [ ] l10n_be 
- [ ] l10n_be_hr_payroll
- [ ] l10n_be_hr_payroll_account
- [x] l10n_be_intrastat - Nothing to do
- [x] l10n_be_invoice_bba - Nothing to do
- [ ] l10n_bo 
- [ ] l10n_br 
- [ ] l10n_ca 
- [x] l10n_ch (OCA project) - By @mreficent - #974 
- [ ] l10n_cl 
- [ ] l10n_cn 
- [ ] l10n_cn_small_business
- [ ] l10n_cn_standard
- [ ] l10n_co 
- [ ] l10n_cr 
- [x] l10n_de - By @reinka - #863 - Nothing to do
- [x] l10n_de_skr03 - By @reinka - #863 - Nothing to do
- [x] l10n_de_skr04 - By @reinka - #863 - Nothing to do
- [ ] l10n_do 
- [ ] l10n_ec 
- [ ] l10n_es 
- [ ] l10n_et 
- [x] l10n_eu_service - Nothing to do
- [x] l10n_fr - By @cubells - #1069 
- [ ] l10n_fr_fec 
- [ ] l10n_fr_hr_payroll
- [ ] l10n_generic_coa
- [ ] l10n_gr 
- [ ] l10n_gt 
- [ ] l10n_hn 
- [ ] l10n_hr 
- [ ] l10n_hu 
- [ ] l10n_in 
- [x] l10n_in_hr_payroll - Nothing to do
- [x] l10n_it - By @tafaRU - #877 
- [ ] l10n_jp 
- [ ] l10n_lu 
- [ ] l10n_ma 
- [x] l10n_multilang (OCA project) - By @mreficent - #939 
- [ ] l10n_mx 
- [x] l10n_nl - By @astirpe - #890 
- [ ] l10n_no 
- [ ] l10n_nz 
- [ ] l10n_pa 
- [ ] l10n_pe 
- [ ] l10n_pl 
- [ ] l10n_pt 
- [ ] l10n_ro 
- [ ] l10n_sa 
- [ ] l10n_sg 
- [ ] l10n_si 
- [ ] l10n_syscohada
- [ ] l10n_th 
- [ ] l10n_tr 
- [ ] l10n_uk 
- [ ] l10n_us 
- [ ] l10n_uy 
- [ ] l10n_ve 
- [ ] l10n_vn 
- [x] link_tracker - By @pedrobaeza - #999
- [ ] lunch 
- [x] mail (OCA project) - By @hbrunn - #790
- [x] mail_tip (Deleted module) - By @pedrobaeza - #990
- [ ] maintenance
- [x] marketing (removed from v9) - By @mreficent - #962 
- [x] marketing_campaign (OCA project) - By @mreficent - #962
- [ ] marketing_campaign_crm_demo 
- [x] mass_mailing - By @pedrobaeza - #943 
- [x] membership (OCA project) - By @mreficent - #862
- [x] mrp - ~~By @PCatinean - #854~~ - By @mreficent - #1076 
- [x] mrp_byproduct - By @hveficent - #1628 
- [x] mrp_operations - By @mreficent - #1076 
- [ ] mrp_repair
- [x] note - By @pedrobaeza - #925 
- [ ] note_pad
- [x] pad (OCA project)  - by @mreficent - #935
- [x] pad_project (OCA project) - by @mreficent - #935
- [x] payment (OCA project) - By @mreficent - #906
- [x] payment_adyen  - By @mreficent - #971 
- [x] payment_authorize  - By @mreficent - #971 
- [x] payment_buckaroo  - By @mreficent - #971 
- [x] payment_ogone  - By @mreficent - #971 
- [x] payment_paypal (OCA project)  - By @mreficent - #971 
- [x] payment_payumoney  - By @mreficent - #971 
- [x] payment_sips  - By @mreficent - #971 
- [x] payment_stripe  - By @mreficent - #971 
- [x] payment_transfer (OCA project)  - By @mreficent - #971 
- [x] point_of_sale (OCA project) - By @mreficent - #959 
- [x] portal (OCA project) - By @mreficent - #972 
- [ ] portal_gamification 
- [x] portal_sale (OCA project) - By @mreficent - #972 
- [x] portal_stock (OCA project) - By @mreficent - #972 
- [x] pos_cache - Nothing to do
- [ ] pos_data_drinks
- [ ] pos_discount
- [ ] pos_mercury 
- [ ] pos_reprint 
- [ ] pos_restaurant
- [x] procurement (OCA project) - By @jbeficent - #820
- [x] procurement_jit - By @pedrobaeza - #926 
- [x] product (OCA project) - By @jbeficent - #819 
- [x] product_email_template - Nothing to do
- [ ] product_expiry
- [ ] product_extended
- [x] product_margin - By @cubells - #1350 
- [ ] product_uos 
- [x] product_visible_discount - By @hbrunn - #655
- [x] project (OCA project) - By @DarioLodeiros / @omar7r - #848 
- [x] project_issue (OCA project) - By @DarioLodeiros / @omar7r - #848
- [x] project_issue_sheet - By @pedrobaeza - #1002 
- [x] project_timesheet - By @pedrobaeza - #928 
- [x] purchase - By @pepetreshere - #838
- [ ] purchase_mrp
- [x] purchase_requisition - By @cubells - #1403 
- [x] rating - By @cubells - #1352 
- [ ] rating_project
- [ ] rating_project_issue
- [x] report (OCA project) - By @pedrobaeza - #804 
- [x] report_intrastat- Nothing to do
- [ ] report_webkit 
- [x] resource (OCA project) - Nothing to do
- [x] sale (OCA project) - By @rruebner - #851
- [x] sale_crm (OCA project) - by @mreficent #941
- [ ] sale_expense
- [ ] sale_layout 
- [x] sale_margin - By @legalsylvain - #1646 
- [x] sale_mrp - By @cubells - #1282 
- [ ] sale_order_dates
- [x] sale_service (deleted module) - By @pedrobaeza - #988
- [ ] sale_service_rating
- [x] sale_stock (OCA project) - By @rruebner / @reinka - #853
- [x] sale_timesheet - By @pedrobaeza - #988
- [x] sales_team (OCA project) - By @pedrobaeza - #821 
- [x] stock (OCA project) - By @pepetreshere - #837 
- [x] stock_account (OCA project) - Nothing to do
- [x] stock_calendar - Nothing to do
- [x] stock_dropshipping - By @cubells - #1081 
- [x] stock_landed_costs - By @pedrobaeza - #2970 
- [x] stock_picking_wave - By @cubells - #1017 
- [x] subscription - Nothing to do
- [x] survey (OCA project) - By @mreficent - #896 
- [x] survey_crm (OCA project) - By @mreficent - #893
- [ ] theme_bootswatch
- [x] theme_default - By @pedrobaeza - #991
- [x] utm (OCA project) - By @pedrobaeza - #823
- [x] warning - Merged across several modules
- [x] web (OCA project) - By @reinka - #861 
- [ ] web_analytics 
- [x] web_calendar (OCA project) - By @gfcapalbo - #799 
- [x] web_diagram (OCA project)  - By @gfcapalbo - #799 
- [x] web_editor - By @pedrobaeza - #992
- [x] web_kanban (OCA project) - By @gfcapalbo - #799 
- [x] web_kanban_gauge (OCA project) - By @gfcapalbo - #799 
- [x] web_planner (OCA project) - Nothing to do
- [x] web_settings_dashboard - By @pedrobaeza - #987
- [x] web_tip - By @NL66278 - #825 
- [x] web_tour - By @pedrobaeza - #824 
- [x] web_view_editor - By @NL66278 - #825 
- [x] website (OCA project) - By @hbrunn - #899 
- [x] website_blog (OCA project) - by @mreficent - #908
- [x] website_crm (OCA project) - by @mreficent - #908
- [ ] website_crm_claim 
- [x] website_crm_partner_assign (OCA project) - by @mreficent - #908
- [x] website_customer - Nothing to do
- [x] website_event (OCA project)  - by @mreficent - #908
- [ ] website_event_questions 
- [x] website_event_sale (OCA project) - by @mreficent - #908
- [x] website_event_track - By @pedrobaeza - #930 
- [x] website_form - By @pedrobaeza - #993
- [ ] website_forum 
- [x] website_forum_doc - Nothing to do
- [ ] website_gengo 
- [x] website_google_map (OCA project) - by @mreficent - #908
- [x] website_hr (OCA project) - Nothing to do
- [ ] website_hr_recruitment
- [x] website_issue - By @pedrobaeza - #994
- [x] website_links - By @pedrobaeza - #995
- [ ] website_livechat
- [x] website_mail (OCA project) - by @mreficent - #908
- [x] website_mail_channel - By @hbrunn - #1028 
- [x] website_mass_mailing - ~~By @gfcapalbo - #979~~ By @cubells - #1526 
- [x] website_membership (OCA project) - by @mreficent - #908
- [x] website_partner (OCA project) - by @mreficent - #908
- [x] website_payment - By @pedrobaeza - #1020
- [x] website_portal - By @pedrobaeza - #996
- [x] website_portal_sale - By @cubells - #1400 
- [x] website_project (OCA project) - by @mreficent - #908
- [x] website_project_issue - By @pedrobaeza - #997
- [ ] website_project_issue_sheet 
- [ ] website_project_timesheet
- [ ] website_quote 
- [ ] website_rating_project_issue
- [x] website_sale (OCA project) - By @gfcapalbo - #968 
- [x] website_sale_delivery - By @cubells - #1397 
- [x] website_sale_digital - By @reinka - #902
- [x] website_sale_options - Nothing to do
- [x] website_sale_stock - By @reinka - #900
- [x] website_slides - By @reinka - #887
- [x] website_theme_install - By @reinka - #884
- [x] website_twitter - Nothing to do
- [x] web_tour - Nothing to do

OCA modules
----------

- [x] OCA/sale-workflow: sale_order_back2draft functionality has been included in core. - By @pedrobaeza - #929 
- [x] OCA/account-invoicing: account_invoice_shipping address - Included in core - By @pedrobaeza - #940 
- [ ] OCA/account-invoicing: account_invoice_refund_option functionality is included in core (see https://github.com/OCA/account-invoicing/pull/229#issuecomment-282720199)
- [ ] OCA/website: website_payment_v10 and website_portal_v10 are now part of the core (as both are backports from this version).
- [x] OCA/website: website_blog_mgmt features are now part of the core - By @chienandalu - #1656 
- [ ] OCA/reporting-engine: report_custom_filename is now part of core.
- [x] OCA/social: mass_mailing_security_group is not needed anymore. You will need to manually assign the "Mass mailing user" permission for granting access. - By @pedrobaeza - #946 
- [ ] OCA/manufacture: mrp_calendar_view renamed to mrp_repair_calendar_view.
- [x] OCA/web: web_easy_switch_company: merged in web - By @cubells - #1079

**Comment by jholze** [comment]
👍

**Comment by jholze** [comment]
@pedrobaeza how can we make progress here ? We are nearly finished with the migration of a project to 8, than we will check 9, so would be cool if we can check together how we can speed up the progress. Maybe a hangout guys ? We can support migration to 10 a lot i think.

**Comment by pedrobaeza** [comment]
9.0 Odoo modules should be dump here with the check for indicating later which ones are already migrated. I normally exclude l10n_xx, as they don't need migration.

**Comment by jleaders** [comment]
If you don't mind me asking, what's the estimated time when this would would be ready?

**Comment by pedrobaeza** [comment]
No plans for now.

**Comment by pedrobaeza** [comment]
Odoo addons list for tracking migration scripts has been included.

**Comment by pedrobaeza** [comment]
Default branch of the project changed to 10.0.

**Comment by pepetreshere** [comment]
Count me up to help in this project!, at Trescloud we have started a migration project up to v10.

I am trying to find out which modules are yet to be migrated, so that we can start collaborating on some of them to get our project done.

But the file [odoo/openupgrade/doc/source/modules90-100.rst](https://github.com/OCA/OpenUpgrade/blob/10.0/odoo/openupgrade/doc/source/modules90-100.rst) doesn't have any list although there were merges to that file ([for example this one](https://github.com/OCA/OpenUpgrade/pull/802/files#diff-b84b38ced0be116f7e0d95f224be0832)). I tried looking at https://doc.therp.nl/openupgrade/modules90-100.html but the list of modules seems missing too.

**Comment by pedrobaeza** [comment]
@pepetreshere, here you have the ToDo list. What more do you need?

**Comment by hbrunn** [comment]
the todo list doesn't tell the full story as we know currently that @NL66278 works on `account` and @jbeficent on `product` if I'm not mistaken. And of course we shouldn't frustrate new contributors with duplicate efforts. @lfreeke could you update the list in this issue please?

@pepetreshere if you're new to the game, welcome! I wrote some things in the previous issue you asked about, if you want to contribute to the 10.0 migration, that's great. We didn't formalize conventions up to now, but stick to a few rules to make our cooperation simpler:

- if you start working on something, announce that here so that the list above can be updated
- one PR per module (if it's not just updating the readme there's nothing to do)
- we want full coverage of migration scripts, add test data if necessary the way some 9.0 scripts did via a yml file (I'm in the train now with very shaky wifi, look this up yourself)
- CI tests do migrate a (n-1) version database with all addons installed and demo data enabled, check the same locally in order not to waste time on figuring out why the CI fails (study .travis.yml for how to handle not yet migrated modules)

**Comment by hbrunn** [comment]
PS: The updated doc script doesn't run currently because of https://github.com/OCA/OpenUpgrade/pull/816, if anyone wants to do the honors...

**Comment by pepetreshere** [comment]
Thanks for your clarification guys, I will keep reviewing the documentation and testing the migration from v8 to v9.

**Comment by lfreeke** [comment]
@hbrunn I'm not a contributor so I cannot update the list. @pedrobaeza will update the list as I discussed this with him today.

**Comment by pedrobaeza** [comment]
We have also talked about marking all the modules that are going to be migrated inside OCA project, so other contributors can focus on doing the rest. I'm with that task right now.

**Comment by pepetreshere** [comment]
Hello @hbrunn and @pedrobaeza, we have successfully migrated the stock module (PR #837) and we would appreciate your review. The same for purchase module which seems to not need anything (PR #838). Our plan is to verify that we are using the right processes and techniques before going on with other modules (hopefully verified if we get to merge stock module).

We found that most modules depends on others already funded by OCA (which is great!) that are not yet done. If you don't mind me asking would it be possible to know the estimated delivery time for each module?

**Comment by pedrobaeza** [comment]
All the work is going to be done before July, @pepetreshere

**Comment by pepetreshere** [comment]
Thats great @pedrobaeza, thanks for the info.

The MRP modules are not marked for migration inside OCA project, these modules seems a bit complex, do you know if anybody is planning to work on these? perhaps we can join efforts to migrate the MRP modules, specially for elaborating the correponding openupgrade_analysis_work.txt files.

**Comment by pedrobaeza** [comment]
Nobody is interested for it right now, me neither. Indeed, the more work in this version is this module.

**Comment by rruebner** [comment]
@pedrobaeza I want to work on the migration for the sale and sale_stock modules.

**Comment by NL66278** [comment]
@pedrobaeza Here my PR for the account module (still WIP): https://github.com/OCA/OpenUpgrade/pull/843

**Comment by astirpe** [comment]
@pedrobaeza I would like to work on modules hr and hr_holidays

**Comment by PCatinean** [comment]
@pedrobaeza I've been assigned the mrp migration

**Comment by MiquelRForgeFlow** [comment]
@pedrobaeza I would like to work on account_voucher

**Comment by omar7r** [comment]
@PCatinean @pedrobaeza Project module will be a 'nothing to do'.

**Comment by omar7r** [comment]
project_issue module -> Nothing to do

**Comment by NL66278** [comment]
@omar7r If there is "Nothing to do"  there is one thing todo: create a PR adding the Nothing to do text to the line for the module in odoo/openupgrade/doc/source/modules90-100.rst

**Comment by pedrobaeza** [comment]
Written down all the assigned modules. Please make your PRs with the "Nothing to do" confirmation in the analysis work file and the documentation.

**Comment by MiquelRForgeFlow** [comment]
PR of account_voucher migration: https://github.com/OCA/OpenUpgrade/pull/845

**Comment by omar7r** [comment]
Ok @NL66278 it is done https://github.com/OCA/OpenUpgrade/pull/848

**Comment by astirpe** [comment]
PR for module hr: #849

**Comment by rruebner** [comment]
PR for sale migration: #851

**Comment by reinka** [comment]
PR for OpenUpgrade: #850

**Comment by reinka** [comment]
PR for sale_stock migration: #853
Did this together with @rruebner

**Comment by astirpe** [comment]
PR https://github.com/OCA/OpenUpgrade/pull/858 is for setting `hr_holidays` to "Nothing to do"

**Comment by reinka** [comment]
PR #859: Setting `account_analytic_default` to `Nothing to do`. Concluding from the `analytic` and `analytic_work` file, the rest has already been done.

**Comment by astirpe** [comment]
@pedrobaeza I would like to work on `hr_attendance` and its pending dependencies (`barcodes`)

**Comment by rruebner** [comment]
@pedrobaeza I want to work on the migration for the delivery module.

**Comment by reinka** [comment]
@pedrobaeza I'd like to work on `web`

**Comment by reinka** [comment]
PR #861 for module `web`

**Comment by MiquelRForgeFlow** [comment]
PR https://github.com/OCA/OpenUpgrade/pull/862 for module `membership`

**Comment by reinka** [comment]
PR #863 for `l10n_de`, `l10n_de_skr03` and `l10n_de_skr04`

**Comment by reinka** [comment]
PR #864 for `base_vat`

**Comment by astirpe** [comment]
PR https://github.com/OCA/OpenUpgrade/pull/865 for `barcodes`

**Comment by reinka** [comment]
PR #867 for `board`

**Comment by reinka** [comment]
PR #868 for `account_accountant`

**Comment by reinka** [comment]
PR #870 for `account_cancel`

**Comment by reinka** [comment]
@pedrobaeza I'd like to work on `hr_timesheet`

**Comment by reinka** [comment]
PR #873 for `base_iban`

**Comment by reinka** [comment]
PR #874 for `document`

**Comment by tafaRU** [comment]
~~I'm working on `hr_gamification`module.~~
PR: https://github.com/OCA/OpenUpgrade/pull/875

**Comment by rruebner** [comment]
PR for delivery migration: #869

**Comment by rruebner** [comment]
PR for contacts migration: #876

**Comment by tafaRU** [comment]
PR for `l10n_it`module: https://github.com/OCA/OpenUpgrade/pull/877

**Comment by rruebner** [comment]
PR for account_budget migration: #878

**Comment by MiquelRForgeFlow** [comment]
PRs for acount_accountant https://github.com/OCA/OpenUpgrade/pull/879  and account_cancel https://github.com/OCA/OpenUpgrade/pull/880 migrations

**Comment by astirpe** [comment]
@pedrobaeza Sorry but for the upcoming weeks I think I will not be able to dedicate any time for migration of module `hr_attendance`, may I ask you to remove my name from `hr_attendance`?

On the other side there is another module that has priority in my to do list: `l10n_nl`. May I ask you to add my name to that module? Thank you!

**Comment by reinka** [comment]
@mreficent #879 and #880 were already done here: #868 and #870

**Comment by MiquelRForgeFlow** [comment]
Ok, I closed mines 😂

**Comment by rruebner** [comment]
PR for account_tax_cash_basis migration: #881

**Comment by rruebner** [comment]
PR for account_tax_python migration: #882

**Comment by rruebner** [comment]
PR for anonymization migration: #883

**Comment by reinka** [comment]
PR for `website_theme_install`: #884

**Comment by rruebner** [comment]
PR for association migration: #885

**Comment by rruebner** [comment]
PR for auth_crypt, auth_ldap and auth_oauth migrations: #886

**Comment by reinka** [comment]
PR for `website_slides`: #887

**Comment by MiquelRForgeFlow** [comment]
PR for <code>base_iban</code>: https://github.com/OCA/OpenUpgrade/pull/888

**Comment by MiquelRForgeFlow** [comment]
PR for both <code>event</code> and <code>event_sale</code>: https://github.com/OCA/OpenUpgrade/pull/889

**Comment by astirpe** [comment]
PR for `l10n_nl`: https://github.com/OCA/OpenUpgrade/pull/890

**Comment by MiquelRForgeFlow** [comment]
PR for both <code>survey</code> and <code>survey_crm</code>: https://github.com/OCA/OpenUpgrade/pull/893

**Comment by reinka** [comment]
PR for `website_sale_stock`: #900

**Comment by reinka** [comment]
PR for `website_sale_digital`: #902

**Comment by MiquelRForgeFlow** [comment]
PR for <code>payment</code>: https://github.com/OCA/OpenUpgrade/pull/906

**Comment by MiquelRForgeFlow** [comment]
PR for several <code>website</code> modules: https://github.com/OCA/OpenUpgrade/pull/908

**Comment by JordiBForgeFlow** [comment]
Updated as per @mreficent  comments

**Comment by MiquelRForgeFlow** [comment]
PR for `pad` and `pad_project` modules: https://github.com/OCA/OpenUpgrade/pull/935

**Comment by pedrobaeza** [comment]
@astirpe are you going to finally work on hr_attendance?

**Comment by astirpe** [comment]
@pedrobaeza in one of my posts above (sent last 31/05/2017) I asked you to remove my name from hr_attendance :) Is it possible?

**Comment by pedrobaeza** [comment]
Oh, I didn't see it. Well, no problem. I will take care of it.

**Comment by MiquelRForgeFlow** [comment]
PR for `sale_crm` module: https://github.com/OCA/OpenUpgrade/pull/941

**Comment by MiquelRForgeFlow** [comment]
PR for `point_of_sale` module: https://github.com/OCA/OpenUpgrade/pull/959

**Comment by sebastienhasa** [comment]
I got a list of used module in Odoo v7 that not mentionned in the list of supported module at the top. How can I know if these modules had change their names, merged or faded away between Odoo 7 to 10?

**Comment by pedrobaeza** [comment]
You can inspect `apriori.py` files across versions, that reflects renaming/merged modules, and mention here for completing the information.

**Comment by pedrobaeza** [comment]
I think we can close this as most relevant modules have been covered, and if someone comes with a missing one, it's not needed to be opened to be tracked here.

If you don't agree, please comment back.
